### ISSUE TITLE
Traefik Support

### ISSUE THREAD

**Issue by evoactivity** [openappsec/openappsec#1]
This is a super interesting project! From the documentation I can see there are already a number of other integrations planned.

I would love to see a traefik plugin for this, is this something that would potentially be supported in the future or is it something the community should look to provide?

**Comment by bilbogh** [comment]
Thanks for your feedback and interest in the project.

We got another request for traefik, but honestly it's not very high on the to-do list right now. We will very glad to support any community member that would like to develop it.

**Comment by egeland** [comment]
I wonder if there's some collaboration that could be done between OpenAppSec and [Curiefense](https://www.curiefense.io/) ?
Would be cool to get a bigger community by combining both, and supporting more integrations, too...

**Comment by bilbogh** [comment]
That's a nice idea. We will look into it. Thanks!
