### ISSUE TITLE
log display functionality does not work (cannot create dev/null)

### ISSUE THREAD

**Issue by dumprop** [openappsec/openappsec#100]
I installed everything according to the instructions, everything works, but the log display functionality does not 

![image](https://github.com/openappsec/openappsec/assets/34004367/56692dc0-47ae-4f7b-bcb7-b5b9cba67686)

Log output:
```
/usr/sbin/open-appsec-ctl: 1820: cannot create dev/null: Directory nonexistent
No logs found
```

The same situation repeats for me with the installation on ubuntu 22.04

**Comment by orianelou** [comment]
Hi @dumprop, 

Thank you for letting us know! We're aware of the issue and we'll have it fixed soon.

Best,

open-appsec team

**Comment by orianelou** [comment]
Hi @dumprop, 

The issue has been resolved, thank you for your involvement!
