### ISSUE TITLE
Nginx-proxy-manager

### ISSUE THREAD

**Issue by fathhhhh** [openappsec/openappsec#107]
Im using nginx proxy manager integrated with the open appsec but what i can see all the attempt didn't blocked by open appsec, the security action only on detect state and not block even i already change the enforcement mode to prevent learn . Refer screenshot below. What can I change to make the WAF block on any security attempt. 

![image](https://github.com/openappsec/openappsec/assets/67633326/51608ea8-4b5a-42d9-8444-5fc9f5bb7c21)

**Comment by orianelou** [comment]
Hi @fathhhhh, 

Thank you for reaching out! I recommend asking NGINX Proxy Manager questions in the [dedicated repo](https://github.com/openappsec/open-appsec-npm/issues) so you could get help from our community as well!

Regarding the issue, could you please verify that the open-appsec local policy file is in the  /appsec-localconfig folder? and run the following command to verify the policy was loaded?
`docker exec appsec-agent open-appsec-ctl -s`
I also recommend making a small change to trigger the policy load, like changing the "minimum confidence level".

If this doesn't solve the issue could send a screenshot of the NGINX Proxy Manager configuration? (You can also send it to info@openappsec.io).

Best,

open-appsec team

**Comment by orianelou** [comment]
Hi @fathhhhh, 

Closing the issue as there's no comment. 

Best, 

open-appsec team
