### ISSUE TITLE
Open-appsec does not work without network connectivity in standalone mode

### ISSUE THREAD

**Issue by bkun31** [openappsec/openappsec#109]
Hi,

I'm using nginx proxy manager integrated with open appsec and I notice that when the agent is started without networks, the agent doesn't work (it doesn't block any attacks). 

When the network is available, open appsec works normally. This should not be normal behavior in standalone mode, which should work in a very closed environment.

I've observed that the agent container tries to reach inext-agents.cloud.ngen.checkpoint.com, even in standalone mode (which is considered a hybrid mode in the launch script).

Do you think this is related? And if so, is it possible to fix this so that nothing is sent to the Internet in standalone mode? In a very closed corporate environment, it's sometimes essential that tools don't send anything over the network for security reasons.

**Comment by orianelou** [comment]
Hi @bkun31, 

The agent reaches out to our fog, you can read more [here](https://docs.openappsec.io/concepts/agents#secure-communication).

As to working without internet connections, this should technically work but hasn't been thoroughly tested, could you please reach out to us at info@openappsec.io, with more details about your deployment? We'll be happy to help! 

Best,

open-appsec team
