### ISSUE TITLE
Open-appsec doesn't work without internet access

### ISSUE THREAD

**Issue by bkun31** [openappsec/openappsec#111]
Hi,

My issue #109 has been closed, however the problem is not solved.

To reproduce:

1. Run docker compose of this [repository]( https://github.com/openappsec/open-appsec-npm) without internet access (by disconnecting the port or disabling the network interface for example).

2. Add any proxy host (accessible without internet)

3. Try to generate an alert with following request `http://proxy-host/?shell_cmd=cat/etc/passwd`.

Nothing happens, no logs are generated and the request is forwarded to the proxy host.

4. Restore internet access, retry the previous request, it's work.

The attack is now blocked, and logs are generated.

Best regards.

**Comment by orianelou** [comment]
Hi @bkun31, 

The agent requires a connection to the internet (our fog) on deployment. For your use case I'll recommend running the compose with connection, making sure the configuration is defined how you want, and then disconnecting, then the agen should continueue protecting yourenvironment without connection.

Best regards,

open-appsec team
