### ISSUE TITLE
Custom rule exemption regex not working

### ISSUE THREAD

**Issue by cbrassel** [openappsec/openappsec#118]
High I set up a custom regex exception like this :

![image](https://github.com/openappsec/openappsec/assets/4759371/311d884e-1e2c-48d6-bf7e-a9d04be78449)

But it seem's not to be working :

![image](https://github.com/openappsec/openappsec/assets/4759371/983f0e9e-5762-4b45-82dd-d38f259c671a)

Did I something wrong ? or any misunderstanding of the way the regex are working ?

Regard's
Claude

**Comment by orianelou** [comment]
Hi, 

You should define the exception based on the indicators, not the parameter name. Please note that the exact exception should be changed to cover all the cases in the logs, for example the "and" could change to "or".
![image](https://github.com/openappsec/openappsec/assets/126462046/412b96f9-f3a9-4e4f-a000-eea66b6453f8)
