### ISSUE TITLE
CPU load in idle state

### ISSUE THREAD

**Issue by TomErnst1972** [openappsec/openappsec#119]
Hi, 

I'm using the docker variant with NPM (nginx proxy manager) in a VM (proxmox, Debian12). the machine has 4x vCPU assigned, with 4GB of RAM.

the machine is idling, no traffic directed to it currently. nevertheless i have lots of cpu cycles in this state.

```
top - 10:35:56 up 6 min,  2 users,  load average: 0,56, 0,33, 0,14
Tasks: 138 total,   4 running, 134 sleeping,   0 stopped,   0 zombie
%Cpu0  :  8,4 us,  1,0 sy,  0,0 ni, 90,6 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st 
%Cpu1  :  7,0 us,  1,3 sy,  0,0 ni, 91,6 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st 
%Cpu2  :  8,0 us,  1,0 sy,  0,0 ni, 91,0 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st 
%Cpu3  :  6,4 us,  0,7 sy,  0,0 ni, 92,9 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st 
MiB Spch:   3914,7 total,   2995,4 free,    641,5 used,    511,9 buff/cache     
MiB Swap:    975,0 total,    975,0 free,      0,0 used.   3273,2 avail Spch

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     ZEIT+ BEFEHL                                                              
   1758 root      20   0   36404  26752  23840 R   5,3   0,7   0:22.22 cp-nano-orchest                                                     
   2191 root      20   0   57656  46108  28260 S   5,3   1,2   0:22.80 cp-nano-http-tr                                                     
   2241 root      20   0   57656  46140  28292 S   5,3   1,2   0:22.59 cp-nano-http-tr                                                     
   2166 root      20   0   57656  45868  28020 S   5,0   1,1   0:22.57 cp-nano-http-tr                                                     
   2216 root      20   0   57656  45892  28040 R   5,0   1,1   0:22.65 cp-nano-http-tr                                                     
   1770 root      20   0   25572  20776  18424 R   4,7   0,5   0:21.32 cp-nano-attachm  
```
<img width="1125" alt="image" src="https://github.com/openappsec/openappsec/assets/74730314/e1f8d38b-02b5-4a34-a358-3a7e17c1d5a8">

if I'm raising the numbers of cpu cores, the issue increases the load linearly, according to the number of cpu cores.

Please advise, what can i do or check? 

many thanks and best regards from a colleague,
Tom Ernst

**Comment by TomErnst1972** [comment]
just a side note: I noticed this behavior regardless if used with docker or NPM, even if I compile all components by myself, the processes consume lots of cpu cycles in idle mode...

i realized this, when i heard my large hypervisor machine firing up its fans due to I was assigning 32 cores to the VM ;-)

**Comment by TomErnst1972** [comment]
before you ask:
```
e3bf6b25b811:/# cpnano -s
---- open-appsec Nano Agent ----
Version: 1.1.0-open-source
Status: Running
Management mode: Cloud management
Policy files: 
    /etc/cp/conf/local_policy.yaml
Policy load status: Success
Last policy update: 2023-12-28T14:46:01.625546

---- open-appsec Orchestration Nano Service ----
Type: Public, Version: 1.1.0-open-source, Created at: 2023-10-05T17:46:48+0000
Status: Running

---- open-appsec Attachment Registrator Nano Service ----
Type: Public, Version: 1.1.0-open-source, Created at: 2023-10-05T17:46:48+0000
Status: Running

---- open-appsec Http Transaction Handler Nano Service ----
Type: Public, Version: 1.1.0-open-source, Created at: 2023-10-05T17:46:48+0000
Registered Instances: 4
Status: Running
```

**Comment by orianelou** [comment]
Hi @TomErnst1972, 

It seems you're using an old version of our agent (we're currently standing on 1.1.7, not 1.0.0). 

Could you please make sure you pull the latest image of the agent and redeploy it? please let me know if the issue persists.

Best, 

Oriane
open-appsec team

**Comment by TomErnst1972** [comment]
still the same with actual agent and recompiled.
![image](https://github.com/openappsec/openappsec/assets/74730314/5b401dbe-c998-4ee9-a84e-c13a6968bb10)

```
top - 18:28:20 up 34 min,  1 user,  load average: 0,68, 0,36, 0,21
Tasks: 140 total,   3 running, 137 sleeping,   0 stopped,   0 zombie
%Cpu0  :  6,1 us,  1,4 sy,  0,0 ni, 92,2 id,  0,0 wa,  0,0 hi,  0,3 si,  0,0 st
%Cpu1  :  7,7 us,  1,0 sy,  0,0 ni, 91,0 id,  0,0 wa,  0,0 hi,  0,3 si,  0,0 st
%Cpu2  :  6,5 us,  1,4 sy,  0,0 ni, 92,1 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
%Cpu3  :  7,4 us,  1,0 sy,  0,0 ni, 91,2 id,  0,0 wa,  0,0 hi,  0,3 si,  0,0 st
MiB Spch:   3914,7 total,   1404,8 free,    754,2 used,   2039,6 buff/cache
MiB Swap:    975,0 total,    974,2 free,      0,8 used.   3160,5 avail Spch

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     ZEIT+ BEFEHL
   8130 root      20   0   39804  28000  24688 S   5,6   0,7   1:42.68 cp-nano-orchest
  69219 root      20   0   64072  46516  28684 R   5,6   1,2   0:17.16 cp-nano-http-tr
  69269 root      20   0   63532  46052  28260 R   5,6   1,1   0:16.61 cp-nano-http-tr
  69244 root      20   0   63532  45988  28196 S   5,3   1,1   0:16.59 cp-nano-http-tr
  69294 root      20   0   63532  46016  28224 S   5,3   1,1   0:16.55 cp-nano-http-tr
  54379 root      20   0   26144  22268  18568 S   5,0   0,6   0:39.71 cp-nano-attachm
```
```
058ec5164b3d:/# cpnano -s
---- open-appsec Nano Agent ----
Version: 1.1.7-open-source
Status: Running
Management mode: Cloud management
Policy files:
    /etc/cp/conf/local_policy.yaml
Policy load status: Success
Last policy update: 2024-04-02T16:11:17.589328

---- open-appsec Orchestration Nano Service ----
Type: Public, Version: 1.1.7-open-source, Created at: 2024-03-12T11:09:51+0000
Status: Running

---- open-appsec Attachment Registrator Nano Service ----
Type: Public, Version: 1.1.7-open-source, Created at: 2024-03-12T11:09:51+0000
Status: Running

---- open-appsec Http Transaction Handler Nano Service ----
Type: Public, Version: 1.1.7-open-source, Created at: 2024-03-12T11:09:51+0000
Registered Instances: 4
Status: Running
```

**Comment by topt** [comment]
I have seen similar CPU usage ever since I tested this - now also on latest 1.1.7 version, with no traffic:
![image](https://github.com/openappsec/openappsec/assets/849134/0e4dbd9b-434f-453c-9abe-fb83a7e3359c)
no matter in what version or approach it was running - this acutal screenshot is from a NPM docker. But I saw similar, also if run directly on the host.

**Comment by orianelou** [comment]
Hi @topt and @TomErnst1972, 

We have set a remote session with @TomErnst1972 to further look into this, we'll update here as well. 

Best,

open-appsec team

**Comment by TomErnst1972** [comment]
let me know, when you was able to access my environment, at least today no one logged in... ;-)

**Comment by orianelou** [comment]
Hi @topt  @TomErnst1972, 

We've identified possible improvements to the performance, and hope to have them included in our next versions. 

Will update here as well.

**Comment by TomErnst1972** [comment]
any news regarding this? :-)

**Comment by orianelou** [comment]
Hi @topt, @TomErnst1972, 

We made some improvements to agent in our latest version that should improve the CPU usage in idle state. 

Thank you for your patience and involvement!

**Comment by alepaez** [comment]
Hello @orianelou !
I'm running agent version 1.1.14 and still getting 30% CPU time usage in idle state.

![image](https://github.com/user-attachments/assets/f59ae9a0-8fac-4b7c-ad70-633bd6393301)

Just to ilustrate, this is my production nginx ingress cpu usage atm. 
![image](https://github.com/user-attachments/assets/b2249766-6c47-4941-b441-db51586d7c58)
