### ISSUE TITLE
cp-nano-http-transaction-handler.log no such file error

### ISSUE THREAD

**Issue by tomp332** [openappsec/openappsec#12]
After a fresh installation on an Ubuntu Server 22.04 LTS , trying to view the logs for a sanity check comes up with the following error:

```
> open-appsec-ctl --view-logs

/var/log/nano_agent/cp-nano-http-transaction-handler.log? : No such file or directory
```

![image](https://user-images.githubusercontent.com/47506972/218039332-c0a21433-7c8c-409d-9c52-3fb45124e702.png)

**Comment by nekromantik** [comment]
how did you fix? I got same issue
