### ISSUE TITLE
Redis Sentinel Error in Learning Deployment

### ISSUE THREAD

**Issue by ksgnextuple** [openappsec/openappsec#120]
Hi

I have installed openappsec with Kong using the helm chart.

Getting the below error in the learning deployment

``` {"eventTime":"2024-04-09T18:24:45.395Z","eventName":"log","eventType":"Code Related","eventAudience":"Internal","eventAudienceTeam":"","eventFrequency":"","eventLogLevel":"error","eventSource":{"fogId":"","fogType":"","eventTraceId":"","tenantId":"","agentId":"","eventSpanId":"","codeLabel":"","issuingFunction":"main.main","issuingFile":"/app/cmd/server/main.go","issuingLine":"51","eventId":""},"eventData":{"stateKey":"","eventMessage":"Failed to inject dependencies! Error: Failed to connect to sentinel redis: Connection to redis sentinel could not be made: Cannot reach Redis, failing health check: redis: all sentinels specified in configuration are unreachable","messageData":{}},"eventTags":[],"eventPriority":"Medium","eventSeverity":"Critical"}
```

Anything that requires to be configured? Did not see anything in the values.yaml or documentation.

**Comment by ksgnextuple** [comment]
Oh sorry sending the logs again:

{"eventTime":"2024-04-10T11:03:21.247Z","eventName":"log","eventType":"Code Related","eventAudience":"Internal","eventAudienceTeam":"","eventFrequency":"","eventLogLevel":"info","eventSource":{"fogId":"","fogType":"","eventTraceId":"","tenantId":"","agentId":"","eventSpanId":"","codeLabel":"","issuingFunction":"openappsec.io/redis.(*Adapter).ConnectToSentinel","issuingFile":"/app/dependencies/openappsec.io/redis/redis.go","issuingLine":"64","eventId":""},"eventData":{"stateKey":"","eventMessage":"Creating new Redis Sentinel client","messageData":{}},"eventTags":[],"eventPriority":"Medium","eventSeverity":"Info"}
redis: 2024/04/10 11:03:21 sentinel.go:514: sentinel: GetMasterAddrByName master="mymaster" failed: dial tcp: address tcp/<redis-port>: unknown port
{"eventTime":"2024-04-10T11:03:21.315Z","eventName":"log","eventType":"Code Related","eventAudience":"Internal","eventAudienceTeam":"","eventFrequency":"","eventLogLevel":"error","eventSource":{"fogId":"","fogType":"","eventTraceId":"","tenantId":"","agentId":"","eventSpanId":"","codeLabel":"","issuingFunction":"main.main","issuingFile":"/app/cmd/server/main.go","issuingLine":"51","eventId":""},"eventData":{"stateKey":"","eventMessage":"Failed to inject dependencies! Error: Failed to connect to sentinel redis: Connection to redis sentinel could not be made: Cannot reach Redis, failing health check: redis: all sentinels specified in configuration are unreachable","messageData":{}},"eventTags":[],"eventPriority":"Medium","eventSeverity":"Critical"}

**Comment by ksgnextuple** [comment]
I was not able to find any documentation related to configuring the learning-deployment, any leads would help. I just used the latetst helm chart to deploy

**Comment by nahum-perman** [comment]
Hi @ksgnextuple 
a fix will be released soon.
for the meanwhile you can install/upgrade by adding 
  --set appsec.learning.image.tag=1.1.7 --set appsec.storage.image.tag=1.1.7
  to the helm install/upgrade command

**Comment by ksgnextuple** [comment]
Sure @nahum-perman will try it out.

**Comment by orianelou** [comment]
Hi, 

Issue was fixed in our latest release (1.1.9)
