### ISSUE TITLE
How to Intercept attack requests on nginx

### ISSUE THREAD

**Issue by roycyz** [openappsec/openappsec#123]
I just load the ngx_cp_attachment_module.so  to nginx configure file. Then run the waf-comparison-project to attack it. But all requests was passed and the log files recorded only like '{"eventTime": "2024-04-15T08:45:08.054","eventName": "Check Point Nano-service started","eventSeverity": "Info","eventPriority": "Medium","eventType": "Event Driven","eventLevel": "Log","eventLogLevel": "info","eventAudience": "Security","eventAudienceTeam": "","eventFrequency": 0,"eventTags": ["Informational"],"eventSource": {"agentId": "Unknown","eventTraceId": "","eventSpanId": "","issuingEngineVersion": "1.1.8-open-source","serviceName": "HTTP Transaction Handler","serviceId": "1"},"eventData": {"logIndex": 2,"serviceName": "HTTP Transaction Handler"}}'.

**Comment by orianelou** [comment]
Hi, 

Have you configured a reverse proxy? You can follow the instructions here - https://docs.openappsec.io/troubleshooting/troubleshooting-guides/agent-fails-to-recognize-http-transactions-with-nginx

**Comment by roycyz** [comment]
Yes, i did.But it's not work.My configure like these. 
 location / {
        proxy_set_header Host  $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Accept-Encoding '';
        proxy_pass http://pweb;
       }
Clicking the url with '?shell_cmd=cat/etc/passwd' return normal page.


> Hi @roycyz,
> 
> Have you configured a reverse proxy? You can follow the instructions here - https://docs.openappsec.io/troubleshooting/troubleshooting-guides/agent-fails-to-recognize-http-transactions-with-nginx

**Comment by roycyz** [comment]
I'm accessing the nginx's ip and port.

**Comment by orianelou** [comment]
Hi @roycyz, 

I'm closing this issue as we're waiting for your response, please reopen once you've attached the needed details.
