### ISSUE TITLE
open-appsec is not working after installation also 

### ISSUE THREAD

**Issue by deeska-singh** [openappsec/openappsec#125]
i integrated the open-appsec for kong Oss in ubuntu ...I followed the official document and it was successfully installed also but when i am sending the malicious request to my services through  kong ...it is getting pass and showing 200 status code ...why ? it should block the requests

**Comment by orianelou** [comment]
Hi @deeska-singh, 

This can happen as open-appsec has multiple modes, prevent and detect, in detect mode (which is the default), malicious requests are logged and not blocked.

you can read more about how to track learning here - https://docs.openappsec.io/how-to/track-learning-and-move-from-learn-detect-to-prevent
If you're using local management you'll need to adjust the policy file, read more here - https://docs.openappsec.io/getting-started/start-with-linux/configuration-using-local-policy-file.

You can also strat in prevent mode by adding the flag --prevent to the installer, read more here https://docs.openappsec.io/getting-started/start-with-linux/install-open-appsec-for-linux#mode-1-automatic-installation-of-open-appsec-and-adding-attachment-plugin-to-nginx-kong
