### ISSUE TITLE
Minimum system requirements info

### ISSUE THREAD

**Issue by stegojulia** [openappsec/openappsec#126]
It would be great if you could provide minimum system requirements for running the agent.

**Comment by orianelou** [comment]
Hi @stegojulia,

As a rule of thumb, we can process ~500 requests per second, per CPU core, however, it is recommended to check the machine load and adjust accordingly.

The following are suggested configurations, how ever we have deployment running on smaller instances successfully. 

Minimal configuration: 2vCPU, 4GB RAM, 10GB Disk

Recommended configuration: 4vCPU, 8GB RAM, 20GB Disk
