### ISSUE TITLE
Add node selector and tolerations to learning deployment

### ISSUE THREAD

**Issue by hspinos** [openappsec/openappsec#127]
We are provisioning open-appsec through a custom Terraform module and use a helm_release block to pass in custom helm values. We wanted to control what nodes the learning and shared storage deployment pods were scheduled onto but it seems those fields are missing from the template files: https://github.com/openappsec/openappsec/blob/main/build_system/charts/open-appsec-k8s-nginx-ingress/templates/learning-deployment.yaml#L19-L72

Can nodeSelector and tolerations be added to the template file so they can be passed in through values file? To maintain full IaC, we had to create a solution using provisioners which seemed extremely counterproductive given the nature of helm charts.

This already exists for appsec deployment: https://github.com/openappsec/openappsec/blob/main/build_system/charts/open-appsec-k8s-nginx-ingress/templates/appsec.yaml#L292-L297

**Comment by orianelou** [comment]
Hi @hspinos, 

Thank you for the suggestion! We'll look into adding this to our next versions.

**Comment by orianelou** [comment]
Hi, this was added as part of our 1.1.13 release
