### ISSUE TITLE
It would be awesome to have a snap version of opensec so it can be deployed on ubuntu servers easily.

### ISSUE THREAD

**Issue by sbe-arg** [openappsec/openappsec#128]
As stated in title would be awesome to have a snap official package.

**Comment by orianelou** [comment]
Hi @sbe-arg, 

You can use our installer for a quick one-command deployment on Ubuntu, you can read more here - https://docs.openappsec.io/getting-started/start-with-linux/install-open-appsec-for-linux#mode-1-automatic-installation-of-open-appsec-and-adding-attachment-plugin-to-nginx-kong

**Comment by sbe-arg** [comment]
@orianelou i'm aware of that, but is not a snap
