### ISSUE TITLE
In Declarative Mode. When adding Asset through local_policy.yaml through Specific Rule

### ISSUE THREAD

**Issue by epaphrasmakoko** [openappsec/openappsec#130]
In Declarative Mode. When adding Asset through local_policy.yaml through Specific Rule there is an issue
1st.  Because when you use fully managed portal and add an asset, the asset will be seen in Asset tab also in main dashboard 
2nd.  Also when adding an asset in full managed portal one can add alot of features like name of asset, tags, all URLs that are based on that particular asset eg an asset can have multiple URLs to be accessed but this is not in declarative mode
In delcarative mode when you add an asset the name of the url becomes the name of the asset

3rd.  since the asset is added form declarative mode this means it can not be seen in asset tab in visibility mode in portal and this lead to when downloading the fully policy form the portal the policy will differ from that is inside the server policy.json

How do i add multiple urls in the asset in delcrative mode as it is in fully managed mode also names of assets

**Comment by orianelou** [comment]
Hi, 

caused by issue #129, I will update there.
