### ISSUE TITLE
Tuning Decisions don't go away

### ISSUE THREAD

**Issue by ervee** [openappsec/openappsec#131]
Hi,

I have 1 Agent, 1 Profile and 3 Assets (a /webmail, /nextcloud and "the rest", all on the same FQDN) in Learn/Detect mode, SaaS managed.
I use the Docker Agent and nginx containers on a dedicated VPS.

Once in a while I need to review Tuning Suggestions and mark them as Malicious or Benign. They then move to the "Tuning Decisions" section. Normally they disappear from there, but for a couple of days now they don't and they stay in the Tuning Decisions section. I rebooted the VPS with the 2 Docker Containers to see if that would fix the issue but it doesn't.

This is the second time this has happened. The first time I destroyed the Agent container and rebuilt it. That seemed to have worked then, but I don't like to do this every time this happens :)

The profile configuration shows that the agent upgrade is set to automatic (and shows version 1.1.9) though on the Agent page the "isLatestVersion" shows "false". But that always seems to be the case. Not sure if this is related.

Could this be a bug or am I doing something wrong?

**Comment by orianelou** [comment]
Hi @ervee, 

Could you please send us the Tenant ID and screen shot or recording of the issue, to info@openappsec.io? we'll look into this, as this seems to be a UI issue I don't think you did anything wrong (nor that rebooting the agents will fix it). 

Thanks!

**Comment by ervee** [comment]
Hi @orianelou , I have sent the information to the provided email address.

**Comment by ervee** [comment]
Enforcing the policy (top right of the page) solved the issue. I feel like an idiot :) though it was not that obvious in the UX.
