### ISSUE TITLE
Openappsec Crowdsec Nginx proxy manager bouncer

### ISSUE THREAD

**Issue by tltglitch** [openappsec/openappsec#133]
I have an openappsec local install for nginx proxy manager and it works great. But when i intergrate with crowdsec, crowdsec decisions do work on and off. Sometimes when an ip is block by crowdsec, opensec nginx proxy manager lets it through and when crowdsec block expires openappsec nginx proxy manager does not allow ip to access resource.

Here is the errors i see the in the openappsec cp-nano-crowdsec-aux.err  logs:

,"eventName":"log","eventType":"Code Related","eventAudience":"Internal","eventAudienceTeam":"","eventFrequency":"","eventLogLevel":"error","eventSource":{"fogId":"","fogType":"","eventTraceId":"9d931524-49c5-4bd7-91b6-a47ce400226f","tenantId":"5bb22ed4-e399-4b11-b9d4-c028d11d67ef","agentId":"","eventSpanId":"","codeLabel":"","issuingFunction":"gitlab.ngen.checkpoint.com/Ngen/fog-msrv-crowdsec-aux/internal/pkg/intelligence.(*Adapter).SendInvalidations","issuingFile":"/builds/Ngen/fog-msrv-crowdsec-aux/internal/pkg/intelligence/intelligence.go","issuingLine":"180","eventId":"","callingService":"fog-msrv-crowdsec-aux"},"eventData":{"stateKey":"","eventMessage":"Failed to send invalidations ({InvalidationsData:[{Class:data Category:cloud Family:ip Group:crowdSec Order: Kind: MainAttributes:[map[ipv4Addresses:[XX.XX.XX.XX]] ObjectType:asset SourceID: TenantID: InvalidationType:delete}] InvalidateByAgentIdentity:true}) to intelligence: Non-OK HTTP code returned from Post request to intelligence (500) with body: ({\"messageId\":\"1337-001\",\"message\":\"Internal Server Error\",\"referenceId\":\"9d931524-49c5-4bd7-91b6-a47ce400226f\",\"severity\":\"High\"})","messageData":{}},"eventTags":[],"eventPriority":"Medium","eventSeverity":"Critical"}

Here is my yaml file for docker:

appsec-agent:
    container_name: appsec-agent
    image: 'ghcr.io/openappsec/agent:latest'
    network_mode: service:appsec-npm
    ipc: host
    restart: unless-stopped
    environment:
      # adjust with your own email below
      - user_email=wowwow@gmail.com
      - nginxproxymanager=true
      - autoPolicyLoad=true
      - CROWDSEC_ENABLED=true
      - CROWDSEC_MODE=prevent
      - CROWDSEC_LOGGING=enabled
      - CROWDSEC_API_URL=http://10.100.20.25:8080/v1/decisions/stream
      - CROWDSEC_AUTH_METHOD=apiKey
      - CROWDSEC_AUTH_DATA=ldjsnksdnk;nd;ksnasknfklsdankfdsna
    volumes:
      - ./appsec-config:/etc/cp/conf
      - ./appsec-data:/etc/cp/data
      - ./appsec-logs:/var/log/nano_agent
      - ./appsec-localconfig:/ext/appsec
    command: /cp-nano-agent --standalone

Also the moment crowdsec is added it becomes slow. Please can you assist me with this issue ?

My docker instance is the only docker instance running on an 8gb intel atom pc only used for nginx proxy manager openappsec

**Comment by orianelou** [comment]
Hi @tltglitch, 

Thank you for reporting the issue, we'll look into this and we'll update

**Comment by tltglitch** [comment]
any updates ?

**Comment by tltglitch** [comment]
I didnt mean to close the issue

**Comment by orianelou** [comment]
Hi, 

We identified a possible issue, we hope to have a solution as part of our next release

**Comment by orianelou** [comment]
Hi @tltglitch, 

Hi, we released a fix to our integration with Crowdesc, please note you'll need to redeploy the agent to get the fix. 

Thank you for notifying us and helping us improve!

**Comment by Anttibay** [comment]
@tltglitch have you managed to make this work? For me, I cant seem to get openappsec to react on manual decisions from crowdsec and neither crowdsec sees prevent alerts by openappsec. However, cscli metrics show traffic. In addition, I also noticed significant performance decrease for using the apps behind Proxy Manager.

**Comment by tltglitch** [comment]
@Anttibay my apologies for the delayed response. I moved away from Openappsec. I am back to crowdsec as they have better support both from the community and the organization itself. Thank you

**Comment by orianelou** [comment]
Hi @tltglitch, @Anttibay,

We highly value our community and sincerely apologize for the inconvenience you’ve experienced. We hope you will consider using open-appsec again to complement the protection of your environment alongside CrowdSec.

Regarding false positives, could you please verify that you are using our Advanced Machine Learning mode? You can find more information here: [Advanced Machine Learning Model](https://docs.openappsec.io/getting-started/using-the-advanced-machine-learning-model).

As for CrowdSec, we are aware of the current limitations and are working diligently to release a new version with the necessary fixes within the next week.

Concerning the learning stage, it is on our short-term roadmap. If you provide us with your emails (you can reach us at info@openappsec.io), we would be happy to grant you early access.

We apologize once again for any inconvenience caused.

Best,

Oriane 

The open-appsec team
