### ISSUE TITLE
Kong helm-chart template errors

### ISSUE THREAD

**Issue by uavila** [openappsec/openappsec#134]
When I deploy the chart available at the url https://downloads.openappsec.io/packages/helm-charts/kong/open-appsec-k8s-kong-latest.tgz I receive this error:
`Error: parse error at (open-appsec-kong/templates/appsec.yaml:177): unexpected ":=" in command
`
Previously the chart worked correctly. However, using the build_system/charts/open-appsec-kong/ files from the repo works fine.

**Comment by orianelou** [comment]
Hi @uavila, 

We recreated this, and it will be fixed in our next version

**Comment by orianelou** [comment]
Hi, 

This issue is now fixed, thank you for reporting this!
