### ISSUE TITLE
Build Errors in environment.cc

### ISSUE THREAD

**Issue by brettsh** [openappsec/openappsec#143]
I'm currently attempting to build open-appsec on an Amazon L2 (aarch64) instance using these commands:

**git clone https://github.com/openappsec/openappsec.git
cd openappsec/
cmake -DCMAKE_INSTALL_PREFIX=build_out .
make install
make package**

I've installed all the external dependencies. In CMakeLists.txt, I've modified the library path so the build is looking for aarch64 libraries, not x86_64.

However, when I run "make install" I get errors like these:
```
/opt/openappsec/core/environment/environment.cc: In member function ‘virtual std::__cxx11::string Environment::Impl::getCurrentHeaders()’:
/opt/openappsec/core/environment/environment.cc:254:52: error: expected unqualified-id before ‘&’ token
         } catch (const boost::uuids::entropy_error &e) {
                                                    ^
/opt/openappsec/core/environment/environment.cc:254:52: error: expected ‘)’ before ‘&’ token
/opt/openappsec/core/environment/environment.cc:254:52: error: expected ‘{’ before ‘&’ token
/opt/openappsec/core/environment/environment.cc:254:53: error: ‘e’ was not declared in this scope
         } catch (const boost::uuids::entropy_error &e) {
```
                                                     ^
I gather Amazon Linux and aarch64 aren't currently supported. However, does anyone have any suggestions how I might fix these errors? Thanks.

**Comment by orianelou** [comment]
Hi @brettsh, closing this ticket as we didn't get a response, feel free to reopen once you can share the details

**Comment by decioaalves** [comment]
Same problem here.
I'm currently attempting to build open-appsec on an AlmaLinux 8.10, and stops in the exact same problem.
