### ISSUE TITLE
Strugling to put in place some exceptions 

### ISSUE THREAD

**Issue by cbrassel** [openappsec/openappsec#146]
Hi,
I have detects like this :
![image](https://github.com/openappsec/openappsec/assets/4759371/2cac4394-1c72-4f2d-9e6a-798c19d0f6bd)
and a exception rule like this : 
![image](https://github.com/openappsec/openappsec/assets/4759371/c39cd0ec-104e-42da-b82a-309bd08a9aa6)

But it seem's I'm not matching the rule but I don't understand why.
Any Idea ?

Regard's
Claude

**Comment by Boris-Rozenfeld** [comment]
Hey @cbrassel, please use a valid regex such as
field_cke_unik_1\[.]\[value]

If you are using regex, it's recommended to validate them on sites like regex101.com before implementation.
