### ISSUE TITLE
Error with nginx update after updating open-appsec - Resolved

### ISSUE THREAD

**Issue by siilitman** [openappsec/openappsec#149]
Just gone to update openappsec on Debian 11 so I could also update the nginx.

Downloaded the latest open-appsec-install and ran with --auto which succeeded with no errors
Did a config check on nginx, it was ok and the sites behind the WAF were working ok

When I upgraded the nginx to  nginx (1.27.0-2~bullseye) I get the following 

`nginx: [emerg] module "/usr/lib/nginx/modules/ngx_cp_attachment_module.so" version 1024000 instead of 1027000 in /etc/nginx/nginx.conf:1`

Below is line 1 and 2 in the conf file
```
load_module /usr/lib/nginx/modules/ngx_cp_attachment_module.so;
load_module /usr/lib/nginx/modules/open_appsec_ngx_module.so;
```
If I comment out line 1 the error shifts to line 2

`nginx: [emerg] module "/usr/lib/nginx/modules/open_appsec_ngx_module.so" version 1024000 instead of 1027000 in /etc/nginx/nginx.conf:2`

If I comment out both lines then nginx test passes and the service will run ok after I restart

Has anyone else encountered this issue?
Is it going to be a problem having those two modules disabled in the config?

Note that I'm using the nginx mainline stable repository

**Comment by orianelou** [comment]
Hi @siilitman, 

Can you please test again while commenting out the second line? as the updated module is the first one?
And yes, without this module enabled open-appsec won't inspect the traffic passing through the NGINX. 

Thank you!

**Comment by siilitman** [comment]
If I uncomment line 1, I get the following
nginx: [emerg] module "/usr/lib/nginx/modules/ngx_cp_attachment_module.so" version 1024000 instead of 1027000 in /etc/nginx/nginx.conf:1

Is it worth me rolling back to nginx 1.26 for now?

**Comment by siilitman** [comment]
I've had a play with different versions of nginx and it looks like it's wanting v1.24 which is no longer available!
I may look at doing a clean install as I have all the sites backed up!

**Comment by siilitman** [comment]
The clean install did the trick!

**Comment by orianelou** [comment]
Hi, 

I'm happy to hear this was resolved!
