### ISSUE TITLE
The combination of ol 9.4 on x86_64 is unsupported. Please see docs.openappsec.io

### ISSUE THREAD

**Issue by felwehedi** [openappsec/openappsec#152]
I am attempting to install open-appsec on oracle linux 9 but I am getting the below error :
open-appsec for NGINX, Kong and APISIX Installer v1.2245.1
For release notes and known limitations check:
https://docs.openappsec.io/release-notes
Searching local NGINX…
nginx version found: 1.26.1-2.el9.ngx
The combination of ol 9.4 on x86_64 is unsupported. Please see docs.openappsec.io

Is this because oracle linux is not supported or red hat linux 9.4 is not supported since oracle linux is just oracle rebranding of red hat linux 9.

**Comment by orianelou** [comment]
Hi @felwehedi, 

We're aware of the issue and we'll release a fix soon, for an imidate solution I recommend switching to a docker based deployment.

**Comment by orianelou** [comment]
Hi, the issue was solved in release 1.1.16
