### ISSUE TITLE
NGINX reverse proxy (including open-appsec attachment)

### ISSUE THREAD

**Issue by cm91** [openappsec/openappsec#157]
Hi,

i've tested the new Unified Docker Image which combined NGINX + Agent in one Image/Container. Just wanted to share a few findings, which probably need some fixes for future releases

I was able to deploy the container and it showed up as agent in the cloud management.

After creating a new asset which i did assign to the Profile for unified agents, the step "Publish and Enforce Policy" fails with an error:
**Critical Error when enforcing policy initiated by <my-email-address>. Check Point will look into this and contact you.**
`Message: This is embarrassing. We have a back-end error. We are going to look into it ASAP
Reference ID: c78c8042-b13b-4ebf-a7ec-aa7e0b0796af
Code: internal-server-error
Tenant ID: org_DCRqDFyDPRRWyDr9
Time: Tue, 09 Jul 2024 08:20:18 GMT`

Another problem is, that after re-creating the stack (docker-compose down && docker-compose up) the agent does register itself with a new UID even with persistent config and data folders.
This doesn't happen with the two-containers setup.

**Comment by orianelou** [comment]
Hi @cm91, 

Thank you for trying out our new deployment option and for the feedback, this is super valuable to us as this deployment is still in beta, we'll look into this and update!

**Comment by orianelou** [comment]
Hi @cm91, 

The issue has been fixed, for the fix to apply please create a new profile (and delete the existing profile before enforcing).

Best, 

Oriane
The open-appsec team
