### ISSUE TITLE
GeoIP Blocking not working without Central Dashboard Token Integration

### ISSUE THREAD

**Issue by ksgnextuple** [openappsec/openappsec#158]
We are using the latest version of KongAppsec. Noticed one issue where the GeoIP blocking based on Country Codes is not working as expected when the integration with the Central Appsec Dashboard is not done,

When I do integrate it starts working, not sure what's wrong here. Is there any restriction on this feature?

**Comment by orianelou** [comment]
Hi @ksgnextuple, 

Country-based Exception rules are only supported in managed tenants (Declarative / Management) - you can find all our none limitations here https://docs.openappsec.io/release-notes#limitations

**Comment by ksgnextuple** [comment]
Thanks for the reply, would it be available in the future?
