### ISSUE TITLE
Recommended approach to monitor agent on Linux?

### ISSUE THREAD

**Issue by jiriteach** [openappsec/openappsec#162]
Hi - Are there any recommendations on the best approach to monitor the open-appsec Nano Agent on Linux? Noticed once that the server had started by the agent had failed to start.

Can check - 
`open-appsec-ctl --status`

But is there any other ways without having to call this all the time? Is there an API to wall the SaaS platform to check?

Thanks

**Comment by orianelou** [comment]
Hi, 

Currently, we do not have an API exposed, we recommend verifying the installation has succeeded in and upgrade.
