### ISSUE TITLE
annotations for security headers

### ISSUE THREAD

**Issue by gopi1713** [openappsec/openappsec#163]
HI team,
How to add security header on kubernetes for ingress  for 

Content-Security-Policy
X-Frame-Options

**Comment by orianelou** [comment]
Hi @gopi1713, 

This is an NGINX capability, that isn't affected by open-appsec, you can check the NGINX ingress docs for more information - https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#configuration-snippet
