### ISSUE TITLE
Incident ID, of the block-page, where to check the log.

### ISSUE THREAD

**Issue by mg-i-cyb-sec** [openappsec/openappsec#165]
Greetings,
when the blocking page appears, an Incident ID is reported as in the attached image. However, it is not clear where to check the incident id. Because from the "event view" of the WEBUI, no reference to the incident id is reported.

Furthermore, the BLOCK PAGE is not always shown, you have to refresh the page several times to make the block page appear with the Incident ID. 
Attached are the images of the BlockPage with the related incident id.
Thank you for the support.
Greetings

![image](https://github.com/user-attachments/assets/4f4df905-4dd4-44f2-94e6-620d0b7a3470)

**Comment by orianelou** [comment]
Hi @mg-i-cyb-sec, 

Regarding searching the Web UI, you can get the incident ID by clicking on the log card, you can also search base on it
![image](https://github.com/user-attachments/assets/3102122d-8b97-414a-a2bc-c92f23a18ff2)
![image](https://github.com/user-attachments/assets/d9eca1e1-70a4-424b-94d2-7129be472c14)

As to the block page not working on the first try, can you please share the browser you're using? Also, please send some additional information to info@openappsec.io so we can further investigate the issue.

1. edit /dev/shm/cp_nano_http_attachment_conf
2. set dbg_level to 0
3. run nginx -s reload
4. recreate the issue
5. set the dbg_level back and reload NGINX.
6. Check the NGINX error log, and send it to us if any errors appear. 

Best, 

Oriane

The open-appsec team

**Comment by orianelou** [comment]
Hi @mg-i-cyb-sec, 

Thank you, once we get the additional info we'll investigate. Generally, it is possible to search for logs based on Incident ID, could you please also attach your tenant ID and we'll see if there's any issues on our back end, do you have any other issues regarding our logging?

Thank you!

**Comment by orianelou** [comment]
Hi, @mg-i-cyb-sec, 

I'm closing this issue for now, feel free to reopen when you can send the relevant information
