### ISSUE TITLE
Asset with IP instead of hostname not working

### ISSUE THREAD

**Issue by andi98** [openappsec/openappsec#172]
Hello,
I tried to test openappsec in a dev environment and stuck for over an hour with a problem: in the cloud console no assets where appearing and if I created them manually they stuck yellow "not connected to any agent".

I found the problem now myself, I think this is a bug: I did not have a FQDN for my server and only used it via IP address. I even put the IP address as "server_name" in the Nginx configuration, but it didn't work out. After changed the IP to a hostname it works instantly.

My configuration:
Agent version: 1.1.15-open-source
OS version: Debian 12.2
nginx version: nginx/1.22.1
open appsec installed with `--auto --prevent --token $TOKEN` flags

![image](https://github.com/user-attachments/assets/33029c32-e9a2-4c18-ae8e-a68f547830d9)

Not working Nginx config 1:
```
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}
}
```
Not working Nginx config 2:
```
server {
	listen 80;

	server_name 10.0.30.86;

	root /var/www/html;
	index index.html;

	location / {
		try_files $uri $uri/ =404;
	}
}
```
Working Nginx config:
```
server {
	listen 80;
	server_name appsec-test.local;
	root /var/www/html;
	index index.html;
	location / {
		try_files $uri $uri/ =404;
	}
}
```

**Comment by orianelou** [comment]
Hi @andi98, 

Assets only appear when using declarative mode or switching from local to managed mode. When you provide a token to the installer you need to configure the assets in the Web UI. 

If the asset is not connected to the agent the issue could be that the profile was not chosen when creating the asset. 

Regarding the NGINX configuration, please keep in mind that you should have proxy_pass configured for open-appsec to check the traffic. 

Best, 

The open-appsec team
