### ISSUE TITLE
The combination of ubuntu noble on x86_64 is unsupported. Please see docs.openappsec.io

### ISSUE THREAD

**Issue by eonebuka** [openappsec/openappsec#175]
I am trying to install open-appsec on Ubuntu 24.04 noble but am getting this error:

open-appsec for NGINX, Kong and APISIX Installer v1.2245.1
For release notes and known limitations check:
https://docs.openappsec.io/release-notes
Searching local NGINX…
nginx version found: 1.26.0-1-noble
The combination of ubuntu noble on x86_64 is unsupported. Please see docs.openappsec.io

Can anyone help me troubleshoot this installation?

**Comment by orianelou** [comment]
Hi @eonebuka, 

Can you please share the output of nginx -V? We'll look into this!

**Comment by eonebuka** [comment]
Hi @orianelou, this is the output:

nginx version: nginx/1.26.0
built by gcc 13.2.0 (Ubuntu 13.2.0-23ubuntu4) 
built with OpenSSL 3.0.13 30 Jan 2024
TLS SNI support enabled

**Comment by orianelou** [comment]
Hi, 

The issue is now resolved. Thank you for your patience!

**Comment by secureme71** [comment]
I have same issue on Ubuntu 24.04:

open-appsec for NGINX, Kong and APISIX Installer v1.2245.1
For release notes and known limitations check:
https://docs.openappsec.io/release-notes
Searching local NGINX…
nginx version found: 1.24.0-2ubuntu7
Unsupported nginx version: 1.24.0-2ubuntu7. Please see docs.openappsec.io

**Comment by eonebuka** [comment]
@orianelou Thank you very much!
