### ISSUE TITLE
open-appsec-ctl: line 1713: [: : integer expression expected

### ISSUE THREAD

**Issue by mikenye** [openappsec/openappsec#176]
Hi,

When attempting to apply a policy with open-appsec-ctl, I receive the following error:

```
# /usr/sbin/open-appsec-ctl -ap
/usr/sbin/open-appsec-ctl: line 1713: [: : integer expression expected
Policy didn't changed. Policy path: /etc/cp/conf/local_policy.yaml
```

When running with `bash -x`, I can see that the variable `last_local_policy_modification_time` does not appear to be set:

```
...<snip>...
+ is_apply_policy_needed
+ '[' /etc/cp/conf/local_policy.yaml '!=' /etc/cp/conf/local_policy.yaml ']'
++ stat -c %Y /etc/cp/conf/local_policy.yaml
+ local_policy_modification_time=1724305329
+ '[' 1724305329 -eq '' ']'
/usr/sbin/open-appsec-ctl: line 1713: [: : integer expression expected
+ '[' -z ']'
+ return 1
+ '[' 1 -eq 1 ']'
+ echo 'Policy didn'\''t changed. Policy path: /etc/cp/conf/local_policy.yaml'
Policy didn't changed. Policy path: /etc/cp/conf/local_policy.yaml
+ exit 0
```

See `+ '[' 1724305329 -eq '' ']'` immediately before the error.

Looking at line 1713:

```bash
    if [ "${local_policy_modification_time}" -eq "${last_local_policy_modification_time}" ] || [ -z ${last_local_policy_modification_time} ]; then
```

How can I fix this?

My environment info:

```
# /usr/sbin/open-appsec-ctl --status
---- open-appsec Nano Agent ----
Version: 1.1.15-open-source
Status: Running
AI model version: Simple model V1.0
Management mode: Cloud management (Visibility mode)
Agent ID:
Profile ID:
Policy files:
    /etc/cp/conf/local_policy.yaml
Policy load status: Success
Last policy update: None

---- open-appsec Orchestration Nano Service ----
Type: Public, Version: 1.1.15-open-source, Created at: 2024-07-24T06:21:17-0700
Status: Running

---- open-appsec Http Transaction Handler Nano Service ----
Type: Public, Version: 1.1.15-open-source, Created at: 2024-07-24T06:21:17-0700
Status: Ready
```

Red Hat Enterprise Linux release 9.4 (Plow)
nginx version: nginx/1.20.1

Thanks.

**Comment by chkp-nadavd** [comment]
Hi @mikenye 
The following change in /usr/sbin/open-appsec-ctl , in [is_apply_policy_needed()](https://github.com/openappsec/openappsec/blob/main/nodes/orchestration/package/open-appsec-ctl.sh#L1713), will allow policy to be updated (after a policy file modification).

Change line #1713:
`if [ "${local_policy_modification_time}" -eq "${last_local_policy_modification_time}" ] || [ -z ${last_local_policy_modification_time} ]; then`
To:
`if [ "${local_policy_modification_time}" == "${last_local_policy_modification_time}" ]; then`

**Comment by mikenye** [comment]
Thanks so much @orianelou!

**Comment by enspiro** [comment]
Hi,

i receiving this error which is similar to the one above.

`/usr/sbin/open-appsec-ctl:` 1713: [: 1741165024: unexpected operator`

`open-appsec-ctl --status
---- open-appsec Nano Agent ----
Version: 1.1.23-open-source
Status: Running
AI model version: Advanced model V2.0
Management mode: Cloud management (Visibility mode)
Agent ID: 9eadf084-276d-4114-b14c-2aba1ff4162d
Profile ID: 50cab2bd-dc8b-9dd9-1067-97beaff4b644
Policy files: 
    /etc/cp/conf/local_policy.yaml
Policy load status: Success
Last policy update: 2025-03-06T15:36:07.591636
`

Line 1713:
`if [ "${local_policy_modification_time}" == "${last_local_policy_modification_time}" ]; then`
