### ISSUE TITLE
Nextcloud - Login issue 

### ISSUE THREAD

**Issue by secureme71** [openappsec/openappsec#181]
Environment: Appsec Linux NGINX Playground - Ubuntu 22.04 and Nextcloud 29.x

After the installation of Appsec, everything works fine except the login: "Temporary error. Please try again."

If I stop the agent and start agent again, I can login only one time because the appsec is loading. I don't see any blocked requested in the logs and I have tried also to switch from "Prevent" policy to "Detect" policy but nothing changes.

**Comment by orianelou** [comment]
Hi @secureme71, 

Will it be possible to share access to the playground you've used or elaborate on your set-up?

**Comment by secureme71** [comment]
What information do you need? It is not possible to access to linux machine for security reason.

**Comment by secureme71** [comment]
I have seen the issue is related to CSRF protection and error disclosure feature. In general web application doesn't work if I try to prevent "high and above" attacks, it cannot display files so I need to set only "critical" attacks.
