### ISSUE TITLE
How is the classification of HTTP requests carried out during learning?

### ISSUE THREAD

**Issue by msepczuk** [openappsec/openappsec#183]
I need an explanation, which I did not find explicitly in the tutorial. In detect-learn mode, WAF learns HTTP traffic. How does WAF know that a given traffic is correct and another is malicious? To teach WAF to an application, it needs to be fed with many requests (both correct and malicious, with malicious being a percentage less), and during this learning, the classification of correct and malicious traffic must occur. On this basis, detection then takes place in prevent-learn mode.

**Comment by orianelou** [comment]
Hi, 

You can find more information about our machine-learning model here - https://www.openappsec.io/post/deep-dive-into-open-appsec-machine-learning-technology
