### ISSUE TITLE
Web UI (SaaS) learning is not updated.

### ISSUE THREAD

**Issue by lidarbtc** [openappsec/openappsec#184]
![1](https://github.com/user-attachments/assets/18dfb8cd-f944-4c3b-95a7-acd081e53599)
1. Learn tab
![2](https://github.com/user-attachments/assets/11925b10-c8a2-4172-9285-97476e364fa3)
2. Monitoring tab

I got 7.7k requests in monitoring tab for last 24 hours, but in learn tab it's not updating and stuck at 43 requests.

**Comment by orianelou** [comment]
Hi @lidarbtc, 

Can you please share the traffic per passet?
![image](https://github.com/user-attachments/assets/5de14bdf-2219-4b06-84b3-19889b05d7f5)


Alsp, can you please share Tenant ID and asset name, by sending an email to info@openappsec.io?

**Comment by lidarbtc** [comment]
> Hi @lidarbtc,
> 
> Can you please share the traffic per passet? ![image](https://private-user-images.githubusercontent.com/126462046/365426996-5de14bdf-2219-4b06-84b3-19889b05d7f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODc1MjMsIm5iZiI6MTcyNTc4NzIyMywicGF0aCI6Ii8xMjY0NjIwNDYvMzY1NDI2OTk2LTVkZTE0YmRmLTIyMTktNGIwNi04NGIzLTE5ODg5YjA1ZDdmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwOTIwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjFmZDMyZDhiM2Y0Mjg3NTMzMTEwY2Y0YWNkZDYzMDhhN2U5NDc5MDE2Mjc3MThlMDZjNDZmOTA3MDIwY2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R3DlsLD9IIHg2DsNVW7VQx9HMjjN0BO0xB4xePiyb2E)
> 
> Alsp, can you please share Tenant ID and asset name, by sending an email to [info@openappsec.io](mailto:info@openappsec.io)?

I have sent mail, thank you
