### ISSUE TITLE
Using ML model independently

### ISSUE THREAD

**Issue by rahulbs123** [openappsec/openappsec#191]
Hi,

I wanted to explore openappsec's capabilities, particularly I was interested in the ML model. 
Can i use the ML model independently of the solution.  Is there a HTTP or any other interface through which i can send entire HTTP request/features and get a verdict on whether its malicious or not ? 

If this is not possible, can you let me know where do i start looking into the code to see the part thats responsible for recieving http data from the attachment (may be from nginx ) and deciding whether to let the packet in or out ?

Thanks in advance!

**Comment by chkp-ogonda** [comment]
There is no independent interface for verdict without an attachment. You can look at /components for the code.

**Comment by orianelou** [comment]
Hi, 

The process in charge of giving the verdict is the HTTP transaction handler, you can read more on our agents architecture here - https://docs.openappsec.io/concepts/agents#http-transaction-handler-nano-service, the code can be found here - https://github.com/openappsec/openappsec/tree/main/nodes/http_transaction_handler
