### ISSUE TITLE
A lot error messages in /var/log/nano_agent/k8s-log-file-handler.sh.err

### ISSUE THREAD

**Issue by JoeHorn** [openappsec/openappsec#194]
https://github.com/openappsec/openappsec/blob/b58f7781e653d5e3d33d6245b986826e4a82ba4c/nodes/http_transaction_handler/package/k8s-log-file-handler.sh#L10

This line of code create a log following messages in /var/log/nano_agent/k8s-log-file-handler.sh.err .
![image](https://github.com/user-attachments/assets/58bf6e65-1761-4b3a-a477-506dd52cde17)

**Comment by orianelou** [comment]
Hi @JoeHorn, 

We're looking into this. 
As a work around you can: 
1. Delete the file:
2. Add a file named: /var/log/nano_agent/cp-nano-http-transaction-handler.log1

Thank you for reporting this, and my apologies for the inconvenience. 

The open-appsec team

**Comment by JoeHorn** [comment]
> Hi @JoeHorn,
> 
> We're looking into this. As a work around you can:
> 
> 1. Delete the file:
> 2. Add a file named: /var/log/nano_agent/cp-nano-http-transaction-handler.log1
> 
> Thank you for reporting this, and my apologies for the inconvenience.
> 
> The open-appsec team

Thank you.

I take 2nd. work around, and following are my cp-nano-http-transaction-handler logs.

![image](https://github.com/user-attachments/assets/7e09249f-1e29-45a2-a1a4-dad14d51f3f3)

The `?` might be replaced with `*` ?

**Comment by mdunc** [comment]
Can this k8s-log-file-handler script be disabled completely in non-kubnernetes setups?  We're just using plain old docker.

**Comment by orianelou** [comment]
solved in latest release
