### ISSUE TITLE
Is ML model already built with default agent installation with Nginx?

### ISSUE THREAD

**Issue by Blason** [openappsec/openappsec#2]
Hi Team,

I have nginx 1.23.2 and installed openappsec agent from my.openappsec.io and wondering if default installation supports ML algorithm by default? Or it does support only with compilation with git clone?

**Comment by bilbogh** [comment]
Yes. A basic model is provided as part of the repository. It is recommended for use in Monitor-Only and Test environments.

An advanced model which is more accurate and recommended for Production use, can be downloaded from https://my.openappsec.io/ , User Menu->Download advanced ML model. This model updates from time to time and you will get an email when these updates happen.

**Comment by Blason** [comment]
Yes - I already did that. However how do I use this? Do I need to compile those again as instructed on gihub?

**Comment by bilbogh** [comment]
See the step by step instruction in the readme file within the tgz that you downloaded. It is different for NGINX and for k8s.
