### ISSUE TITLE
SWAG agent issues

### ISSUE THREAD

**Issue by Flyingfufu** [openappsec/openappsec#201]
Hi,

Installed SWAG openappsec-integrated over docker. The installation went fine and the first policy enforcement went through problem less.

After few iteration (6) while adding some apps, I suddenly started to received the following error message :
`Message: This is embarrassing. We have a back-end error. We are going to look into it ASAP
Reference ID: 2022fea5-fd29-4116-a3c0-92ef841d1fef
Code: internal-server-error
Tenant ID: org_ktp0doQCwxkcPoUX
Time: Sat, 09 Nov 2024 16:26:06 GMT`

Restarting the container, recreating the a new profile from scratch or changing the token is of no help. The policy are not incrementing anymore :
![image](https://github.com/user-attachments/assets/ba69e8d1-cfb4-455a-9ae9-17be9fff2bef)
Also, in contrary to what is stated in the profile, only 1 agent exist

The command  open-appsec-ctl -s result is :
`---- open-appsec Nano Agent ----
Version: 1.1.19-open-source
Status: Running
AI model version: Advanced model V1.0
Management mode: Cloud management (Visibility mode)
Agent ID: 90eed0d5-c22c-4614-b594-b7b8b92b2cd1
Profile ID: 82c988c0-d473-011f-addb-8a4614dd0ff8
Policy files: 
    /etc/cp/conf/local_policy.yaml
Policy load status: Error
Last policy update: 2024-11-09T15:40:01.518770`
`---- open-appsec Orchestration Nano Service ----
Type: Public, Version: 1.1.19-open-source, Created at: 2024-11-06T21:32:51+0000
Status: Running`
`---- open-appsec Attachment Registrator Nano Service ----
Type: Public, Version: 1.1.19-open-source, Created at: 2024-11-06T21:32:51+0000
Status: Running``
`---- open-appsec Http Transaction Handler Nano Service ----
Type: Public, Version: 1.1.19-open-source, Created at: 2024-11-06T21:32:51+0000
Registered Instances: 6
Status: Running`

https://downloads.openappsec.io/ result is :
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>1N530F6AJ0P6EE20</RequestId>
<HostId>FmHiu8mFUlYBWwzqJOWXD1P+tgcQNiC4NxqvXlYmSgqtwgj3JIK1/aHdt1llCmAE4aROqZ+dSso=</HostId>
</Error>`
while https://inext-agents.cloud.ngen.checkpoint.com/ answer is 403 !

Any help or tips will be greatly appreciated.

**Comment by danyard14** [comment]
Hello @Flyingfufu,

Thank you for reaching out. Upon reviewing your case, it appears you're setting an exception (source IP - *) that is not currently supported.

![image](https://github.com/user-attachments/assets/ea68c684-ab0a-4eda-bfa5-e19e52a7b959)

We are aware of this issue and are actively working on a solution to improve visibility for unsupported exceptions.

If you’d like to discuss potential workarounds or solutions, please feel free to contact us at [info@openappsec.io](mailto:info@openappsec.io).

Thank you for your patience and understanding.

Best regards.

**Comment by Flyingfufu** [comment]
Thanks for the feedback. removing the condition fixed the installation.
However, one more question : how to block all IP (or country) except some specific ones ? Any easy way ?

**Comment by Flyingfufu** [comment]
Thanks for the feedback. removing the condition fixed the installation.
