### ISSUE TITLE
Too many false positives from WAF?

### ISSUE THREAD

**Issue by NazgulCoder** [openappsec/openappsec#206]
![Senza titolo](https://github.com/user-attachments/assets/e3c3286e-9c87-495e-a956-6d9a52fefb4c)

Hi, How is this even possible that it raises so many false flags?

For reference, website is behind cloudflare and it's a normal Wordpress website selfhosted with Docker, and I am using NPM with your integration

Thank you very much for your help in advance

**Comment by NazgulCoder** [comment]
I just noticed Open AppSec is not what I need since the behaviour analysis is too heavy. With a simple Flood (even with Cloudflare in front of it which blocks 90% of the attack) it pushes openappsec agent and npm attachment at 100% CPU (or even more), and basically kills the entire Reverse Proxy.

Don't get me wrong. With NPM Vanilla my Host doesn't go down under DDoS attacks even with 50M PPS

**Comment by orianelou** [comment]
Hi @NazgulCoder, 

open-appsec, unlike traditional WAF is using Machine Learning as the security engine. Meaning the model needs to learn when first deployed and could raise some false positive, this is why we recommend starting in prevent mode and only after some time moving to prevent - you can read more here - https://docs.openappsec.io/how-to/track-learning-and-move-from-learn-detect-to-prevent

Regarding DDoS, you can set up rate limiting to protect your application from DDoS read more here -   https://docs.openappsec.io/how-to/setup-rate-limit-ddos-control

**Comment by NazgulCoder** [comment]
> Hi @NazgulCoder,
> 
> open-appsec, unlike traditional WAF is using Machine Learning as the security engine. Meaning the model needs to learn when first deployed and could raise some false positive, this is why we recommend starting in prevent mode and only after some time moving to prevent - you can read more here - https://docs.openappsec.io/how-to/track-learning-and-move-from-learn-detect-to-prevent
> 
> Regarding DDoS, you can set up rate limiting to protect your application from DDoS read more here - https://docs.openappsec.io/how-to/setup-rate-limit-ddos-control

Hey thanks for the reply.

Regarding the WAF, I gave it a try again but even after several days (i get around 100 visits daily for each site, for a total of 2k visits per day) it still was getting many false flags.

Regarding the DDoS, I tried also your rate limit but I'm pretty sure the openappsec module implementation is just "too heavy" that drains too many resources.

Like I said, same DDoS attack with NPM and NPM + OpenAppSec have totally different behaviour and resources usage
