### ISSUE TITLE
Unsupported nginx version: 1.24.0-2ubuntu7.1

### ISSUE THREAD

**Issue by An0nX** [openappsec/openappsec#208]
root@ubuntu-server:~# ./open-appsec-install --auto
open-appsec for NGINX, Kong and APISIX Installer v1.2245.1
For release notes and known limitations check:
https://docs.openappsec.io/release-notes
Searching local NGINX…
nginx version found: 1.24.0-2ubuntu7.1
Unsupported nginx version: 1.24.0-2ubuntu7.1. Please see docs.openappsec.io

**Comment by orianelou** [comment]
Hi @An0nX, 

You're nginx version isn't listed in the supported versions found here - https://docs.openappsec.io/getting-started/start-with-linux/install-open-appsec-for-linux

To avoid compatibility issues we recommend a docker based deployment.

**Comment by An0nX** [comment]
I already understand this, I need to understand whether there will be an update with the addition of this version, or I will have to break the compatibility check and install it like this
