### ISSUE TITLE
Can I use openappsec to compile and install nginx?

### ISSUE THREAD

**Issue by uepuer** [openappsec/openappsec#209]
Because of the program environment need to use the compilation and installation of nginx, but add openappsec plugin in the installation, prompted to find the version of nginx, please ask me how to adjust, I compile nginx version is 1.22.0

**Comment by orianelou** [comment]
Hi @uepuer, 

open-appsec can integrate with nginx, the main distributions already have a supported version in our [Linux installer ](https://docs.openappsec.io/getting-started/start-with-linux/install-open-appsec-for-linux), and in Docker we provide an [enhanced NGINX container](https://docs.openappsec.io/getting-started/start-with-docker).

**Comment by uepuer** [comment]
Sorry, I have seen the compilation and installation of the agent, but it only mentioned how to add it to docker for use, and did not explain how to introduce it in the compiled nginx and install the token to connect to the saas.

**Comment by orianelou** [comment]
Hi, 

Regarding connecting to NGINX, this is explained in the attachment repo https://github.com/openappsec/attachment

Regarding connecting to SaaS once you can follow our docs as normal https://docs.openappsec.io/getting-started/using-the-web-ui-saas
