### ISSUE TITLE
Pod termination takes too long

### ISSUE THREAD

**Issue by meyerf99** [openappsec/openappsec#25]
Hello Open-Appsec Team,

A few months ago I have already placed the problem around restarts from the pods with the product owner of Open-Appsec. According to a feedback, a restart or deletion of a pod should be relatively fast by now. Unfortunately, it is still very slow with the version 4.1.4 and sometimes you prefer to kill the pod itself. The problem itself is still due to a health check of the controller.

Thanks for looking at the problem.

**Comment by orianelou** [comment]
Hi, 

Our Helm chart is based on the [NGINX helm](https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx/4.1.4) chart so the "controller.terminationGracePeriodSeconds" is set to default value of 300 seconds. 

You can adjust the grace period using `--set controller.terminationGracePeriodSeconds=3`
