### ISSUE TITLE
table is not initialized

### ISSUE THREAD

**Issue by meyerf99** [openappsec/openappsec#27]
Hello Open-AppSec Team,

With Helm version 4.1.4 I have the following errors in the controller and no Ingress works.
`|2023-05-17T11:50:54.369: is_static_resource_request@ngx_cp_static_content.c:229 [uid 2 | pid 26] <session id 783> | Cannot determine whether request is for a static resource: static resources' table is not initialized`

I'm not sure if it has something to do with the error, why the individual Ingress do not work but according to the logs at least nothing arrives at the controller.

The exact same configuration with an old DEV Open-AppSec version everything works fine.

**Comment by WrightNed** [comment]
Thanks for letting us know, we will try to recreate the issue and resolve it.
Could you please share with us your configuration and which older version worked for you?

**Comment by meyerf99** [comment]
> Thanks for letting us know, we will try to recreate the issue and resolve it. Could you please share with us your configuration and which older version worked for you?

Hi @WrightNed 
Yeah sure, I have now tried all variations of configurations including those in the official documentation. In the end I always get the same error and it looks like the Nginx Ingress is not running correctly.

I have used the more or less identical parameters. Therefore I am now temporarily switched :(

**End configuration**
`helm install open-appsec-k8s-nginx-ingress-4.1.4-rel-latest.tgz \
   --create-namespace \
   --namespace appsec \
   --name-template open-appsec \
   --set appsec.mode=managed \
   --set appsec.agentToken="{Token}" \
   --set appsec.persistence.enabled=true \
   --set appsec.persistence.data.size=4Gi \
   --set appsec.persistence.conf.size=4Gi \
   --set appsec.persistence.learning.storageClass.name=azurefile \
   --set appsec.persistence.learning.size=4Gi \
   --set controller.ingressClass="appsec-nginx" \
   --set controller.ingressClassResource.name="appsec-nginx" \
   --set controller.ingressClassResource.controllerValue="k8s.io/appsec-nginx" \
   --set controller.service.loadBalancerIP='{Public IP}' \
   --set controller.replicaCount=2`
   
   In my DEV Kubernetes AKS cluster, I am using the following Docker image versions:
   - [checkpoint/infinity-next-nano-agent:dev-409535](https://hub.docker.com/layers/checkpoint/infinity-next-nano-agent/dev-409535/images/sha256-a453c8e22d3dedb50cd715531c48bf53c5eb67124619c50c1fd260c86b485f19?context=explore)
   - [checkpoint/cp-nano-k8s-nginx-ingress:dev-379404-1.19.2](https://hub.docker.com/layers/checkpoint/cp-nano-k8s-nginx-ingress/dev-379404-1.19.2/images/sha256-38b395c2679bd6b868fa79982dd3147a00fbbe64e56f7f9eb5dce2b75494ad5d?context=explore)

PROD AKS: v.1.26.3
DEV AKS: v.1.23.12

Thank you for your support
Regards,
@meyerf99

**Comment by WrightNed** [comment]
Hi @meyerf99,

Just to update that we've reproduced the issue and are investigating it. The error message itself is benign and we will fix it so it won't continue to be disruptive.

I will continue to update as we learn more about this.

Thanks,
Ned

**Comment by laiqinghua** [comment]
> 你好@meyerf99,
> 
> 只是为了更新我们已经重现了该问题并正在调查它。错误消息本身是良性的，我们将修复它，这样它就不会继续造成破坏。
> 
> 当我们了解更多相关信息时，我将继续更新。
> 
> 谢谢， 内德

---------------------
me too, Is there an estimate for this issue

**Comment by laiqinghua** [comment]
> 你好@meyerf99,
> 
> 只需更新我们已经修复了该问题并正在调查它。错误消息本身是良性的，我们将修复它，这样它就不会继续造成破坏。
> 
> 当我们了解更多相关信息时，我将继续更新。
> 
> 谢谢， 内德

Is there an estimated repair time for this issue

**Comment by orianelou** [comment]
Hi @meyerf99 @laiqinghua,

This issue was fixed, you can use version 1.0.0 for your deployment. 

Thank you for your patience, 

Oriane
