### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by k-e-r-n-e-l-p-a-n-i-c** [openappsec/openappsec#28]
Dear Team,

I was looking for a open source WAF solution for a K8's cluster and your project looks very interesting to me.  Can you please share a timeline for a stable release, if possible? Thank you!

Regards,
Arun Prasad

**Comment by orianelou** [comment]
Hi @k-e-r-n-e-l-p-a-n-i-c, 

We're keeping the beta flag to encourage users to share their feedback on our solution, this shouldn't stop you from using open-appsec. 

We welcome you to test open-appsec and see for yourself, you can also use our [playgrounds](https://www.openappsec.io/playground) to see open-appsec in action!
