### ISSUE TITLE
Unable to register the agent to FOG

### ISSUE THREAD

**Issue by Blason** [openappsec/openappsec#3]
Hi Guys,

I compiled the agent successfully with the codes and tried registering the agent to the FOG however I am consistently getting error.

root@appsec:/opt/build_out# ./install-cp-nano-agent.sh --install --token cp-xx-xxxx.xxxxxxxxx.xxxxxxxxx
Check Point Nano Agent Version 1.0.0 Install Package
Verifying archive integrity...  100%   All good.
Uncompressing...  100%
Fog address='https://inext-agents.cloud.ngen.checkpoint.com'
/usr/bin/which
/usr/sbin/ldconfig

Starting installation of open-appsec Nano Agent [Sun 27 Nov 2022 03:22:16 PM UTC]
Creating env details file
Copying cp-nano-agent binary file to folder: /etc/cp/orchestration/cp-nano-orchestration
Installing the watchdog
Start cp-nano-agent service
Note: in order for the agent to remain active and effective it must connect to the Fog/Cloud at least every 45 days
open-appsec Nano Agent installation completed successfully
Registering open-appsec Nano Agent to Fog..
**open-appsec Nano Agent registration failed**. Failed to register to Fog: https://inext-agents.cloud.ngen.checkpoint.com

**Comment by bilbogh** [comment]
Please send your tenant id to email: info at openappsec.io and we'll look into it. The tenant id can be obtained by clicking the user icon in the UI.

**Comment by Blason** [comment]
Have emailed that separately.

**Comment by Blason** [comment]
resolved

**Comment by kppullin** [comment]
@Blason any details on the resolution?  I've run into the same failure message about a month ago. Wondering if the latest agent fixes this or if it's some other issue.
