### ISSUE TITLE
AWS NLB NGINX Ingress Support

### ISSUE THREAD

**Issue by ccben87** [openappsec/openappsec#31]
Hi, 

I've noticed that when using AWS with NGINX Ingress that the service load balancer is created with an AWS Classic ELB which means that I cannot retrieve the true source IP from pods. If you refer to the setup instructions for AWS (https://kubernetes.github.io/ingress-nginx/deploy/#aws), there is a provided YAML to set this up with AWS NLB but the file will need modifications to work with open-appsec. I would appreciate it if you could address this issue. Thanks.

**Comment by orianelou** [comment]
Hi, 

You can adjust the following keys in our regular NGINX helm chart (by adjusting and applying values.ymal) , this configures an annotation for the service resource switching to the NLB Loadbalancer type and configures it in the way to preserve external source IP: 

controller.service.annotations="{service.beta.kubernetes.io/aws-load-balancer-type: "nlb"}"
controller.service.externalTrafficPolicy=Local
