### ISSUE TITLE
Scrub ip addresses

### ISSUE THREAD

**Issue by roelandvanbatenburg** [openappsec/openappsec#33]
Hi,

We are looking to use open-appsec in our kubernetes cluster instead of Ingress Nginx. However, we have a requirement from GDPR that we should limit the processing of ip addresses. In order to do that we have included [ipscrub](https://github.com/masonicboom/ipscrub) in a custom nginx docker image as a module. Would such a thing also be possible with open-appsec?

Thanks!

**Comment by orianelou** [comment]
Hi,

Thank you for your interest in open-appsec:blush:

Generally, the open-appsec agent doesn’t replace NGINX, it’s a separate service that integrates with an NGINX reverse proxy to provide protection.
 You can read more about the open-appsec agent [here](https://docs.openappsec.io/concepts/agents), and on how to deploy open-appsec on NGINX [here](https://docs.openappsec.io/getting-started/getting-started).

As to the ip-scrub, theoretically, as the hash used allows you to identify requests from the same source, the machine learning algorithm could still learn from your traffic, however, this could decrease the functionality of some of open-appsec's advanced features (for example the CrowdSec integration).  

We love to see new and interesting use cases like yours, and we'll be more than happy to help you deploy open-appsec if decide to proceed with us.
