### ISSUE TITLE
proxy-wasm support

### ISSUE THREAD

**Issue by kesavkolla** [openappsec/openappsec#39]
Lot of reverse proxy servers now has support wasm. Making openappsec as wasm filter will help in integrating with many proxies at once.

**Comment by orianelou** [comment]
Thanks for your feedback! We agree that making open-appsec a WebAssembly filter would greatly improve integration with many reverse proxy servers supporting wasm. We'll carefully consider the suggestion, ensuring security and compatibility.

If you would like to contribute to the project by adding support to more proxies or wasm yourself, we will be very glad to support you (or any community member that would like to develop it), yet we encourage you to reach out using [info@openappsec.io](mailto:info@openappsec.io) before a PR.
