### ISSUE TITLE
NGINX 1.22 

### ISSUE THREAD

**Issue by Ethical-Cronos** [openappsec/openappsec#4]
Hi guys all right? I would like to know if there is any prediction for me to be able to install the sec app with nginx 1.22?

Thank you for understanding

**Comment by bilbogh** [comment]
It should work now on Debian 10(buster) and 11 (bullseye) and on Ubuntu 18(bionic) 20(focal) and 22 (jammy).
If you need another target, please let us know or you can compile yourself per the instructions provided.
In the next days, se'll publish a file with all flavors - the file will update automatically.

**Comment by Blason** [comment]
Does it work with 1.22? I tried already and it says it doesn't work.

Even compile didn't work I guess.

**Comment by Ethical-Cronos** [comment]
> 

I did the tests and it didn't work so much in debian 10 and 11, do I intend to launch it for versions these days?

**Comment by Ethical-Cronos** [comment]
I did the tests and it didn't work so much in debian 10 and 11, do I intend to launch it for versions these days?

> It should work now on Debian 10(buster) and 11 (bullseye) and on Ubuntu 18(bionic) 20(focal) and 22 (jammy). If you need another target, please let us know or you can compile yourself per the instructions provided. In the next days, se'll publish a file with all flavors - the file will update automatically.

**Comment by bilbogh** [comment]
Also list of supported/pre-compiled versions is now available [here](https://downloads.openappsec.io/supported-nginx.txt).

**Comment by Ethical-Cronos** [comment]
Wonderful I am, grateful for the update, from what I saw here the sec app on debian 10 does not have support for Nginx 1.22.1
buster:
		nginx:
			1.18.0-1-buster
			1.18.0-2-buster
			1.19.0-1-buster
			1.19.10-1-buster
			1.19.1-1-buster
			1.19.2-1-buster
			1.19.3-1-buster
			1.19.4-1-buster
			1.19.5-1-buster
			1.19.6-1-buster
			1.19.7-1-buster
			1.19.8-1-buster
			1.19.9-1-buster
			1.20.0-1-buster
			1.20.1-1-buster
			1.20.2-1-buster
			1.21.0-1-buster
			1.21.1-1-buster
			1.21.2-1-buster
			1.21.3-1-buster
			1.21.4-1-buster
			1.21.5-1-buster
			1.21.6-1-buster
			1.22.0-1-buster
			1.23.0-1-buster
			1.23.1-1-buster

> Also list of supported/pre-compiled versions is now available [here](https://downloads.openappsec.io/supported-nginx.txt).

**Comment by bilbogh** [comment]
Correct. It has support for Buster/NGINX 1.22.0, but not 1.22.1.  We can try to add it, but did you look into compiling it yourself?

**Comment by Ethical-Cronos** [comment]
I'll try it again since Wordops recently added support for debian 11

Link: https://github.com/WordOps/WordOps


> Correct. It has support for Buster/NGINX 1.22.0, but not 1.22.1. We can try to add it, but did you look into compiling it yourself?

**Comment by Ethical-Cronos** [comment]
Erro:

NGINX version found: 1.22.1-1ppa-stable
Downloading open-appsec NGINX attachment... stored in '/tmp/open-appsec'
Unsupported NGINX version, for supported platforms, OS and NGINX versions please see docs.openappsec.io
Downloading open-appsec agent... stored in '/tmp/open-appsec'


> Correct. It has support for Buster/NGINX 1.22.0, but not 1.22.1. We can try to add it, but did you look into compiling it yourself?

**Comment by bilbogh** [comment]
We are not able to install 1.22.1, regardless of open-appsec. Please explain how you did it.

**Comment by Ethical-Cronos** [comment]
Well, I use the Wordops microservices stack that comes with a highly customized Nginx, for the security and performance part, I use it to install my Wordopress sites, I'm integrating it with CrowdSec that recognizes the Nginx version perfectly, follow the github link below from Wordops.

Link: https://github.com/WordOps/WordOps

> We are not able to install 1.22.1, regardless of open-appsec. Please explain how you did it.

**Comment by dgambarin** [comment]
Hi @Ethical-Cronos 
The Wordops service you use is not using an official nginx release but as stated in their README - "Custom Nginx build : Nginx 1.22.1 - TLS v1.3 Cloudflare HTTP/2 HPACK & Brotli support"
To install openappsec on this server please follow the instructions in : https://github.com/openappsec/openappsec and https://github.com/openappsec/attachment 
Note that you must install several dependencies first (you can use this command `apt-get update -y && apt-get install -y libgmock-dev libboost-all-dev jq cmake g++ vim git make libssl-dev libpcre2-dev libxml2-dev libcurl4-openssl-dev g++ libgtest-dev wget libpcre3 libpcre3-dev libxslt-dev libgd-dev libgeoip-dev)
