### ISSUE TITLE
Autoinstaller not detecting a supported version

### ISSUE THREAD

**Issue by gruizonestic** [openappsec/openappsec#42]
Hi there!

I'm trying to install open-appsec using the auto installer method `./open-appsec-install --auto`. My server is currently running NGINX version `1.18.0-6ubuntu14.3` on `Ubuntu Jammy 22.04 LTS`. As stated in the supported [pre-compiled versions list](https://downloads.openappsec.io/supported-nginx.txt) the script should find the correct binaries and install them but I keep getting no supported versions found.
```sh
# ./open-appsec-install --auto
open-appsec for NGINX and Kong Installer v1.2245.1
For release notes and known limitations check:
https://docs.openappsec.io/release-notes
Searching local NGINX…
NGINX version found: 
Downloading open-appsec NGINX attachment... stored in '/tmp/open-appsec'
Unsupported NGINX version, for supported platforms, OS and NGINX versions please see docs.openappsec.io
Downloading open-appsec agent... stored in '/tmp/open-appsec'
```
Is this a bug? Also, I can't compile from source code and I expect the script to work as I meet all the requirements.

Thanks.

**Comment by orianelou** [comment]
Hi Guillermo, 

We had an issue with Ubuntu 22, that could have caused this error. The issue was fixed yesterday night. I apologize for the inconvenience. 

Could you please redeploy the agent? As we tested on an environment similar to yours and it worked as it should. If you're still having any issues kindly attach the output of nginx -V and we'll look into this. 

Thanks, 

Oriane - open-appsec team

**Comment by gruizonestic** [comment]
Hi @orianelou,

Thanks for the quick response. I redownloaded the installation script but there are no differences. I also checked for new merges in the repo but I couldn't see anything.

Same output as before.
```sh
# ./open-appsec-install --auto
open-appsec for NGINX and Kong Installer v1.2245.1
For release notes and known limitations check:
https://docs.openappsec.io/release-notes
Searching local NGINX…
NGINX version found: 
Downloading open-appsec NGINX attachment... stored in '/tmp/open-appsec'
Unsupported NGINX version, for supported platforms, OS and NGINX versions please see docs.openappsec.io
Downloading open-appsec agent... stored in '/tmp/open-appsec'
```
Here you have my `nginx -V` output
```sh
# nginx -V
nginx version: nginx/1.18.0 (Ubuntu)
built with OpenSSL 3.0.2 15 Mar 2022
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -ffile-prefix-map=/build/nginx-d8gVax/nginx-1.18.0=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-compat --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --add-dynamic-module=/build/nginx-d8gVax/nginx-1.18.0/debian/modules/http-geoip2 --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_sub_module
```
Please let me know if you need everything else.

Thanks again,

Guillermo Ruiz.

**Comment by orianelou** [comment]
Hi @gruizonestic,

Thank you for providing those details! we'll look into this and keep you updated. 

I apologize for the inconvenience,

Oriane - open-appsec team
