### ISSUE TITLE
Openappsec coredumping

### ISSUE THREAD

**Issue by AdmiraalA** [openappsec/openappsec#49]
OS : RH 9.2
Nginx : nginx -V
nginx version: nginx/1.20.1 ( nginx-1.20.1-13.el9.x86_64 )

Used automated and manual install . 
Selinux on AND off .. same result below

cp-nano-watchdog[34058]: /etc/cp/watchdog/cp-nano-watchdog: line 859: 34911 Aborted                 (core dumped) LD_LIBRARY_PATH=/usr/lib/cpnano/ /etc/cp/orchestration/cp-nano-orchestration --orchestration-mode=hybrid_mode --filesystem_path=/etc/cp --log_files_path=/var/log
Sep 01 22:15:38 zabbix cp-nano-watchdog[34058]: /etc/cp/watchdog/cp-nano-watchdog: line 859: 34924 Aborted                 (core dumped) LD_LIBRARY_PATH=/usr/lib/cpnano/ /etc/cp/attachmentRegistrator/cp-nano-attachment-registrator --filesystem_path=/etc/cp --log_files_path=/var/log
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: Environment
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: DebugIS
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: Version
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: Buffer
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: ShellCmd
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: GenericMetric
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: ConfigComponent
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: InstanceAwareness
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: IntelligenceComponentV2
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: AgentDetails
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: LoggingComp
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: TimeProxyComponent
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: MainloopComponent
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: SignalHandler
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: RestServer
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: Encryptor
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: SocketIS
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: ProtoMessageComp
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: CPUCalculator
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: CPUManager
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: MemoryCalculator
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: MessagingBuffer
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: TenantManager
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: GenericRulebase
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: OrchestrationStatus
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: OrchestrationTools
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: PackageHandler
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: Downloader
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: ServiceController
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: ManifestController
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: UpdateCommunication
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: AgentDetailsReporter
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: DetailsResolver
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: OrchestrationComp
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: HealthChecker
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: HealthCheckManager
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: MessagingDownloaderClient
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: LocalPolicyMgmtGenerator
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: [loadConfiguration@config.cc:587                              | ---] ignoring an illegal configuration argument. Argument: /etc/cp/orchestration/cp-nano-orchestration
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: Opening debug file. File path: /var/log/nano_agent/cp-nano-orchestration.dbg
Sep 01 22:15:38 zabbix cp-nano-watchdog[35031]: Successfully opened debug file. File path: /var/log/nano_agent/cp-nano-orchestration.dbg
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: Environment
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: DebugIS
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: Version
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: Buffer
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: ShellCmd
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: GenericMetric
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: ConfigComponent
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: InstanceAwareness
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: IntelligenceComponentV2
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: AgentDetails
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: LoggingComp
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: TimeProxyComponent
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: MainloopComponent
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: SignalHandler
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: RestServer
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: Encryptor
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: SocketIS
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: ProtoMessageComp
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: CPUCalculator
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: CPUManager
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: MemoryCalculator
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: MessagingBuffer
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: TenantManager
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: GenericRulebase
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [preloadComponents@components_list_impl.h:118                 | ---] Preloading component: AttachmentRegistrator
Sep 01 22:15:38 zabbix cp-nano-watchdog[35044]: [loadConfiguration@config.cc:587                              | ---] ignoring an illegal configuration argument. Argument: /etc/cp/attachmentRegistrator/cp-nano-attachment-registrator

**Comment by orianelou** [comment]
Hi @AdmiraalA, 

Thank you for reaching out! Did you get the same error when using our installer (and have you used our installer after compiling the attachment)?
 
Thanks, 
Oriane

**Comment by AdmiraalA** [comment]
I did it with the installer

**Comment by orianelou** [comment]
Hi @AdmiraalA, 

We're trying to recreate this and we'll update. 

Thank you for your patience, 

Oriane

**Comment by orianelou** [comment]
Hi @AdmiraalA, 

I'm happy to share A variety of Red-Hat versions is now supported, you can find the complete list [here](https://downloads.openappsec.io/packages/supported-nginx.txt).

Oriane
