### ISSUE TITLE
ngx_module_1.18.0-6ubuntu14.3.tar.gz has no content

### ISSUE THREAD

**Issue by scornet256** [openappsec/openappsec#5]
Hello,

I would like to give this a try on Ubuntu 22.04 (Jammy).  
I have NGINX version `1.18.0-6ubuntu14.3` installed which is listed on the [supported versions](https://downloads.openappsec.io/supported-nginx.txt) list.

It seems both the `-auto` flag and the `-download` flag of the `open-appsec-nginx-install` fetches an empty `ngx_module_1.18.0-6ubuntu14.3.tar.gz`.

```
/tmp/open-appsec# ls -ahl
total 22M
drwxr-xr-x  4 root root 4.0K Dec 27 08:03 .
drwxrwxrwt 13 root root 4.0K Dec 27 08:05 ..
drwxr-xr-x  2 root root 4.0K Dec 14 15:16 ngx_module_1.18.0-6ubuntu14.3
-rw-r--r--  1 root root  133 Dec 27 08:02 ngx_module_1.18.0-6ubuntu14.3.tar.gz
drwxr-xr-x  2 root root 4.0K Dec 13 14:19 openappsec
-rw-r--r--  1 root root  22M Dec 27 08:02 openappsec.tar.gz

/tmp/open-appsec# ll ngx_module_1.18.0-6ubuntu14.3
total 8
drwxr-xr-x 2 root root 4096 Dec 14 15:16 ./
drwxr-xr-x 4 root root 4096 Dec 27 08:03 ../
```

Is there a timeline available where the nginx module is available?
Im looking forward giving this product a try!

**Comment by scornet256** [comment]
Removing it from the list some days later without response was quite lame...

**Comment by chkp-noamw** [comment]
Hi,

The supported versions, as well as the list, are automatically generated.
We are working to understand the issue and bring the relevant version back.

**Comment by bilbogh** [comment]
We fixed the issue. Please try again now.
