### ISSUE TITLE
Tracking local learning

### ISSUE THREAD

**Issue by Zibbp** [openappsec/openappsec#50]
Hi,
I'm demoing open appsec for a local-only replacement of Modsecurity. Reading the documentation, part of the process to move from detect to prevent is to [look at the "learning level"](https://docs.openappsec.io/how-to/track-learning-and-move-from-learn-detect-to-prevent). Is there a CLI command that allows viewing this locally without using the SaaS web panel?

**Comment by bilbogh** [comment]
We are working on adding a CLI option for that. It will be available within few weeks. For now, you can only track the learning progress using the web interface.

**Comment by epaphrasmakoko** [comment]
Hello i hope you are still working on this

**Comment by orianelou** [comment]
Hi @Zibbp, and @epaphrasmakoko, 

We've released a beta version - https://docs.openappsec.io/how-to/track-learning-and-local-tuning-in-standalone-deployments let us know if you have any notes!
