### ISSUE TITLE
docker ml model learning data location

### ISSUE THREAD

**Issue by shubhshah01** [openappsec/openappsec#51]
Hi, I'm using open appsec with docker and is connected to the web management portal. I wanted to know how does docker restart or re-running the open-appsec agent docker container affect the learning data ?
Where is the learning data for the ML model stored ? Will docker restart affect it ?

**Comment by bilbogh** [comment]
Hi, when deploying using docker, you should provide a path to a volume that would be mounted for storing persistent information, such as config files, learning data, debugs and logs. This volume would survive restarts. See more information here - https://docs.openappsec.io/getting-started/start-with-docker

**Comment by shubhshah01** [comment]
Thanks.
Also is it necessary for the mounted dirs to be empty ?
I had my vm ready with openappsec configured and all containers running fine and connected to the web management portal.
Next I wanted to reconnect to web management portal for some reason, so i killed and removed the containers (openappsec agent and nginx). and also deleted the connected agent from web portal. Now when i tried to re-run my containers it did not connect to the web management portal. (Also tried creating a new profile and use a new token).

**Comment by orianelou** [comment]
Hi @shubhshah01,

Could you share the error message you encountered while connecting to the management interface? If it's similar to:

```
Configuration contains ingress/asset with URL that already has an asset attached to it in your tenant.
```

Check out our troubleshooting guide [here](https://docs.openappsec.io/troubleshooting/configuration-contains-ingress-asset-with-url-which-already-has-asset-attached-to-it-in-your-tenant) for solutions. 

Thanks, 
Oriane

**Comment by orianelou** [comment]
Hi @shubhshah01, 

Did you get a chance to check my previous response?

Thanks, 

Oriane

**Comment by shubhshah01** [comment]
Hi @orianelou ,
completely missed the notifications.
Yeah, It seems to work now. Don't exactly remember the error message i encountered earlier.
Will check if i can reproduce the error again.

**Comment by shubhshah01** [comment]
Also one question,
In my configured application i now have over 140k requests which open-appsec has detected. Now it shows some tuning suggestions, after i label them as either malicious or benign (I'll label it as benign since most of the requests of severity high or critical are not malicious requests), how would the model learning proceed ? Is there any further step required after labelling the events in order to update the model with latest labellings ?

Thanks for the help!

**Comment by bilbogh** [comment]
You just need to enforce the policy, the rest will happen automtically.

**Comment by shubhshah01** [comment]
Ok Thanks. Is it the same if using advanced ml model with docker ?

**Comment by bilbogh** [comment]
Yes, indeed the same.

**Comment by shubhshah01** [comment]
Hi, sorry for reopening. How do i confirm if installation of advanced ml model is successful and its using it and not the basic model.
I am using docker and nginx.

Below are the docker logs. At the end it has listed the files of the downloaded advanced ml tgz file does that indicate that the config is all ok and its using advanced ml model now ?
![image](https://github.com/openappsec/openappsec/assets/122277028/d14d632e-87c6-4a8e-a6a0-b50c20919138)

**Comment by shubhshah01** [comment]
Hi @bilbogh @orianelou, sorry for commeting after its closed. Tagging since the issue is closed.
How can one confirm if installation of advanced ml model is successful and its using it and not the basic model.
I am using docker and nginx.

Below are the docker logs. At the end it has listed the files of the downloaded advanced ml tgz file does that indicate that the config is all ok and its using advanced ml model now ?
![image](https://github.com/openappsec/openappsec/assets/122277028/2945a10d-9823-4aeb-baf4-d98efe5dbb1b)

**Comment by orianelou** [comment]
Hi @shubhshah01,

No problem at all, and thank you for reaching out. As of now, there isn't a straightforward way to confirm which model is being used from the logs alone.

However, I have good news for you. We are working on implementing a feature that will indicate which model is in use, and it will be included in our next release, scheduled for the following week. 

If you have any more questions or need further assistance, please feel free to ask.

Best regards,

Oriane

**Comment by shubhshah01** [comment]
Great! Thanks for the help.
