### ISSUE TITLE
OpenAppSec is blocking sane URL without any possibility for correction

### ISSUE THREAD

**Issue by kzgrzendek** [openappsec/openappsec#52]
Hi guys, 

This issue is more of a demand of assistance, because I'm maybe missing something.

One of the URL of my application is blocked by OpenAppSec ; I have a 403 return code, but nothing is displaying in the logs of the agent.
As soon as I switch from prevent to learn mode, the page is accessible again. I tried to stay in learning mode a few days in the hope that the model would have learned that the URL is not dangerous, but unfortunately, as soon as I switch back to prevent mode, the page is blocked again.

Here are some details about my installation :  
- OpenAppSec version : 1.0.1, running along an NGinx Ingress Controller in a Kubernetes cluster (installed via the HelmChart as indicated in the documentation).
- Blocked URL : POST method to update the configuration of the application. The pattern of the URL is `https://[APP-HOST]/[APP-VERSION]/ControlCenter/security_settings.php`
- Model used : production model downloaded from OpenAppSec Portal
- Configuration & CRDs : everything is [in that gist](https://gist.github.com/kzgrzendek/403abf65892b965aea1a552e20f92279)

Don't hesitate if you need anything else.

Thank you :)

**Comment by orianelou** [comment]
Hey @kzgrzendek,

Thanks for reaching out! Feel free to share your questions or requests here. 
Thank you for attaching the full configuration, we'll look into your deployment and update you.

Just a quick question: Is the cluster connected to SaaS management? Were you able to see any logs for other requests? 

Appreciate it,

Oriane

**Comment by kzgrzendek** [comment]
Hi @orianelou  :) 

Thanks so much for your reactivity! 

Yes I can see the logs of the agent, notably the part about the URL of the Ingress Controller's probe (which should be blocked, according to the exception I set) : 

```json
{
    "eventTime": "2023-09-12T14:40:34.311",
    "eventName": "Web Request",
    "eventSeverity": "Info",
    "eventPriority": "Low",
    "eventType": "Event Driven",
    "eventLevel": "Log",
    "eventLogLevel": "info",
    "eventAudience": "Security",
    "eventAudienceTeam": "",
    "eventFrequency": 0,
    "eventTags": [
        "Threat Prevention",
        "Web Application & API Protection"
    ],
    "eventSource": {
        "agentId": "59eb7fb1-2e69-451a-9d9f-fc510012194a",
        "eventTraceId": "",
        "eventSpanId": "",
        "issuingEngineVersion": "1.0.1-open-source",
        "serviceName": "HTTP Transaction Handler",
        "serviceId": "1",
        "k8sClusterId": "df2865d8-bcaf-42ef-a191-a379f703666a",
        "assetId": "Any",
        "assetName": "Any"
    },
    "eventData": {
        "logIndex": 326,
        "eventReferenceId": "539ade19-1d05-413f-ad78-115a39613c12",
        "assetId": "Any",
        "assetName": "Any",
        "sourceIP": "127.0.0.1",
        "httpSourceId": "127.0.0.1",
        "sourcePort": 45930,
        "httpHostName": "127.0.0.1:10246",
        "httpMethod": "GET",
        "httpUriPath": "/is-dynamic-lb-initialized",
        "httpUriQuery": "",
        "ruleId": "Any",
        "securityAction": "Detect",
        "waapOverride": "None",
        "practiceType": "Threat Prevention",
        "practiceSubType": "Web Application",
        "ruleName": "Any",
        "practiceId": "e93cccc9-0150-4e76-9739-d10b6fe03670",
        "practiceName": "open-appsec-aphp-eds-ovh-policy/open-appsec-aphp-eds-ovh-practice",
        "waapIncidentType": "",
        "matchedSample": "",
        "matchedLocation": "",
        "matchedParameter": "",
        "waapFoundIndicators": "",
        "matchedIndicators": "",
        "learnedIndicators": "",
        "waapUserReputationScore": 433,
        "waapUserReputation": "Normal",
        "waapUriFalsePositiveScore": 0,
        "waapKeywordsScore": 0,
        "waapFinalScore": 0,
        "waapCalculatedThreatLevel": 0
    }
}
```

Nothing much else, which is surprising because I configured a specific Log Trigger CRD to log as much things as possible (see the gist I shared in my first post).

**Comment by orianelou** [comment]
Hi @kzgrzendek, 

We're looking into it and we'll update you once we have a solution.

**Comment by kzgrzendek** [comment]
Hi @orianelou,

If you need any more information, or even a demo with a quick call, don't hesitate :) 

(You can use the email address in my profile to contact me if you need)

**Comment by kzgrzendek** [comment]
Hi @orianelou :)

Great, thanks! Can't wait to test it :)

**Comment by orianelou** [comment]
Hi, 

This issue has been fixed a while ago, I apologize for not updating this issue.

Best, 

Oriane
