### ISSUE TITLE
[enhancement] HTTP Flood identification

### ISSUE THREAD

**Issue by jes009** [openappsec/openappsec#55]
Good afternoon team,

I notice that many features can perform "open appsec," but only one feature, named rate limit, can protect against DDOS HTTP Flood attacks. Over time, this type of attack has grown. 

For example, Cloudflare can detect and mitigate these attacks, as shown in this mitigation example: 

https://pbs.twimg.com/media/FnvwRBVaUAESTpS?format=png&name=small.

To protect against this type of attack, I propose an idea: when one IP exceeds the rate limit 4 times in less than 2 minutes, it should be blocked to protect the backend. I now believe this is the best approach we can take.

I would like to attempt to create a pull request with this feature, but I think I lack knowledge about the project and require many hours of programming. Please share your perspective and let me know if you find this interesting or need more details.

**Comment by orianelou** [comment]
Hi @jes009,

Thank you for your interest in improving our project's security! We're pleased to inform you that the feature you proposed is already in development (you can read more [here](https://www.openappsec.io/post/developing-web-application-and-api-rate-limiting-using-chatgpt)), and we aim to release it soon. 

If you have any more ideas or suggestions, please feel free to share them with us. Your feedback is important, and we're committed to enhancing open-appsec.

Thanks,

Oriane

**Comment by jes009** [comment]
thanks a lot orianelou, i didn't see this post before, another idea is block request by user agents is a simple feature but is very useful.

thanks another time to hear the community :)

**Comment by 5hin0bi** [comment]
Hello everyone!

I've seen that the feature itself is ready since I could find the document on how to confugre it via the WebUI here: https://docs.openappsec.io/how-to/setup-rate-limit-ddos-control

My question is: is it possible to configure rate-limit rule via the kubernetes CRDS?
This is vital for the IAC approach used in our company. 

Thanks in advance!

**Comment by orianelou** [comment]
Hi @5hin0bi, 

It is not possible yet. We are working on the next versions of CRDs that will allow you to manage Rate Limiting as well.
