### ISSUE TITLE
Installer errors on Ubuntu 22.04

### ISSUE THREAD

**Issue by wwolkers** [openappsec/openappsec#58]
Hi,

when trying to install on Ubuntu 22.04 the installer gives an error:

ubuntu@vm-server:~$ sudo ./open-appsec-install --auto
open-appsec for NGINX and Kong Installer v1.2245.1
For release notes and known limitations check:
https://docs.openappsec.io/release-notes
Searching local NGINX…
NGINX version found: 1.18.0-6ubuntu14.4
Downloading open-appsec NGINX attachment... stored in '/tmp/open-appsec'
Unsupported NGINX version, for supported platforms, OS and NGINX versions please see docs.openappsec.io
Downloading open-appsec agent... stored in '/tmp/open-appsec'
Unsupported OS, for supported platforms, OS and NGINX versions please see docs.openappsec.io

trying to manually download https://downloads.openappsec.io/packages/agent/aarch64/ubuntu/jammy/openappsec-jammy.tar.gz gives me an access denied error.

**Comment by wwolkers** [comment]
looks to be the same error as https://github.com/openappsec/openappsec/issues/42

**Comment by orianelou** [comment]
Hi @wwolkers,

Regrettably, it seems that your NGINX version isn't among the officially supported distributions listed [here](https://downloads.openappsec.io/packages/supported-nginx.txt). Rest assured, we'll consider this for inclusion in our next release.

For a more immediate solution, we suggest either [deploying open-appsec using Docker](https://docs.openappsec.io/getting-started/start-with-docker) to bypass these compatibility concerns or [building the attachment](https://github.com/openappsec/attachment), and getting the agent using the `--download` option of the install script (instead of `--auto` )

If you have any further questions or need assistance with either approach, please don't hesitate to ask.

Best, 
Oriane

**Comment by wwolkers** [comment]
hi @orianelou ,

even if I run a newer version (supported) of nginx I still get the same errors
ubuntu@vm-server:~$ sudo ./open-appsec-install --auto
open-appsec for NGINX and Kong Installer v1.2245.1
For release notes and known limitations check:
https://docs.openappsec.io/release-notes
Searching local NGINX…
NGINX version found: 1.24.0-1-jammy
Downloading open-appsec NGINX attachment... stored in '/tmp/open-appsec'
Unsupported NGINX version, for supported platforms, OS and NGINX versions please see docs.openappsec.io
Downloading open-appsec agent... stored in '/tmp/open-appsec'
Unsupported OS, for supported platforms, OS and NGINX versions please see docs.openappsec.io
ubuntu@vm-server:~$

**Comment by orianelou** [comment]
Hi @wwolkers, 

Could you please let us know which CPU architecture are you using?

Thanks, 

Oriane

**Comment by wwolkers** [comment]
Hi @orianelou ,

This is a VM running on an oracle cloud instance.

Ampere A1 Compute instances (Arm processor)

ubuntu@vm-server:~$ lscpu
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Neoverse-N1
    Model:               1
    Thread(s) per core:  1
    Core(s) per cluster: 4
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r3p1
    BogoMIPS:            50.00
    Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; __user pointer sanitization
  Spectre v2:            Mitigation; CSV2, BHB
  Srbds:                 Not affected
  Tsx async abort:       Not affected

**Comment by orianelou** [comment]
Hi,

I'm sorry to inform you that ARM isn't currently supported. You can keep tabs on our efforts to add ARM support through this open issue: https://github.com/openappsec/openappsec/issues/19.

Thank you for your understanding.

Best regards,

Oriane
