### ISSUE TITLE
2023_01_02 branch seems incomplete

### ISSUE THREAD

**Issue by input-io** [openappsec/openappsec#6]
Hello all,

The [Jan 2th update](https://github.com/openappsec/openappsec/tree/2023_01_02) seems incomplete and not yet fully pushed. For example the [new ML model file](https://github.com/openappsec/openappsec/blob/8bdbd8166c1af6b8323a7608a2d2efcad1519022/components/security_apps/waap/resources/waap.data) seems missing from the repo. 
When will this be done?

Thanks,
input-io

**Comment by chkp-noamw** [comment]
Hi,

We are working to complete the update, and we hope to have it ready in a few days. It currently goes through our testing systems, and once everything it completed it will be merged to back to the main branch.

**Comment by WrightNed** [comment]
Hi @input-io,

The update from Jan 2nd is replaced with the new [Jan 16th](https://github.com/openappsec/openappsec/tree/Jan_16_2023) update. We hope it will be merged to main by the end of the day.

Thanks,
Ned
