### ISSUE TITLE
systemd log cluttered with garbage

### ISSUE THREAD

**Issue by SpiderD555** [openappsec/openappsec#63]
Hi,
Last time I tried to check the status on nano_agent installed on Debian 11 nginx, then I found that I can only see those error messages:
```
Oct 14 15:31:23 waf1 cp-nano-watchdog[2336437]: sh: 1: cpprod_util: not found
Oct 14 15:31:23 waf1 cp-nano-watchdog[2336438]: sh: 1: cpprod_util: not found
Oct 14 15:31:53 waf1 cp-nano-watchdog[2337247]: sh: 1: clish: not found
Oct 14 15:31:53 waf1 cp-nano-watchdog[2337251]: sh: 1: cpprod_util: not found
Oct 14 15:31:53 waf1 cp-nano-watchdog[2337252]: sh: 1: cpprod_util: not found
Oct 14 15:32:24 waf1 cp-nano-watchdog[2338207]: sh: 1: clish: not found
Oct 14 15:32:24 waf1 cp-nano-watchdog[2338211]: sh: 1: cpprod_util: not found
Oct 14 15:32:24 waf1 cp-nano-watchdog[2338212]: sh: 1: cpprod_util: not found
```
Is there any chance those can be suppressed ? Or maybe the watchdog could be modified accordingly ?

**Comment by WrightNed** [comment]
Hi @SpiderD555,

Thanks for reporting this, it will be fix in one of the next releases.

**Comment by orianelou** [comment]
Hi @SpiderD555,

The issue has been fixed

**Comment by SpiderD555** [comment]
@orianelou 
I have just updated openappsec and it seems the clutter is gone. It looks very good now. Thank you
