### ISSUE TITLE
About technical documentation

### ISSUE THREAD

**Issue by progmboy** [openappsec/openappsec#70]
Hi,

Thank you for open source. I am very interested in the technology.
Is there any technical documentation on training and scoring algorithms related to this? The code looks quite difficult to understand.
Another question is, how is the basic model trained? Is there any related information available?
I have read the technical white paper on the website, and the related algorithms are not described very clearly.

**Comment by orianelou** [comment]
Hi @progmboy, 

Our model is trained based on malicious and legitimate traffic sets. You can read more about the technology in this [blog](https://www.openappsec.io/post/deep-dive-into-open-appsec-machine-learning-technology ).

Best,

Oriane
open-appsec team
