### ISSUE TITLE
Http Transaction Handler temporarily unavailable

### ISSUE THREAD

**Issue by bxlxx** [openappsec/openappsec#71]
<img width="1080" alt="image" src="https://github.com/openappsec/openappsec/assets/34093828/391e5106-6813-4556-bd65-70ee43969642">

**Comment by bxlxx** [comment]
I fixed this issue because the cp-nano-http-transaction-handler doesn't find the libgen_core.so.

**Comment by RMackner** [comment]
How did you fix this issue with libngen_core.so?

**Comment by bxlxx** [comment]
> How did you fix this issue with libngen_core.so?

use the command ```find / -name "ngen_core"``` to find the position of so, then copy it to the ```/usr/lib64```
