### ISSUE TITLE
libngen_core.so

### ISSUE THREAD

**Issue by RMackner** [openappsec/openappsec#73]
Seems like I'm missing this library (libngen_core.so) and not finding any information about it on the web or the provided documents. Any help with pointing me in the right direction? Running Nginx 1.25.2 on RHEL 9.2.

**Comment by orianelou** [comment]
Hi @RMackner, 

For the benefit of the community could you please let us know how the issue was solved?

Thank you, 

Oriane
open-appsec team

**Comment by RMackner** [comment]
I did not find a solution, installed a fresh copy of Ubuntu also and got
the same error. Just didn't have the time to troubleshoot this if it was
library issues out of the gate.

**Comment by orianelou** [comment]
Hi, 

We'll be happy to assist you, could you please share the NGINX and Ubuntu versions as well as the full error you've received?

Thanks, 

Oriane
open-appsec team

**Comment by RMackner** [comment]
Currently using RHEL 9.2 and Nginx 1.25.2. Receiving the following error in
the logs when the nano service starts and crashes in a loop.

***@***.***:595                              | ---]
ignoring an illegal configuration argument. Argument:
./cp-nano-attachment-registrator
/builddir/build/BUILD/gcc-11.4.1-20230605/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1115:
std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference
std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() [with _CharT =
char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>;
std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&]:
Assertion '!empty()' failed.

**Comment by orianelou** [comment]
Hi @RMackner,

The issue with deployment on RHEL 9.2 is now fixed. 

Have a great new year!

open-appsec team
