### ISSUE TITLE
ORCHESTRATION_INSTALLATION_SCRIPT="install-cp-nano-agent.sh" files not found

### ISSUE THREAD

**Issue by daniynwa** [openappsec/openappsec#75]
where a file install-cp-nano-agent.sh

I have downloaded Appsec Advanced Model.

followed the steps in the README file, but during the docker build process, the intsall-cp-agent.sh file was not found

![image](https://github.com/openappsec/openappsec/assets/25548516/f28a5f7f-d6e3-450c-b39f-01fe3edb3b3e)

docker logs >>

![image](https://github.com/openappsec/openappsec/assets/25548516/3a75de71-9ec3-4424-88a8-27693878d9a5)

**Comment by orianelou** [comment]
Hi @daniynwa,

Thank you for reaching out, we're looking into the issue. To get your open-appsec deployment up & running in the meantime I recommend running our provided image and following the readme for "Using the advanced model inside docker"
Thank you, 

Oriane
open-appsec team

**Comment by daniynwa** [comment]
okey thank you.

I have successfully upgraded with the advanced model

**Comment by orianelou** [comment]
Hi @daniynwa, 

I'm happy to hear! Did you use the exact instructions from the readme? 

Thank you,

Oriane
open-appsec team

**Comment by daniynwa** [comment]
![image](https://github.com/openappsec/openappsec/assets/25548516/0f117af5-8843-4787-853c-e15ddfb634b3)

why policies in SaaS Cloud are not working and http handler is not running

**Comment by daniynwa** [comment]
after upgrading the agent from basic to advanced mode

**Comment by orianelou** [comment]
Hi @daniynwa, 

The transaction handler is fired when the first packets arrive at agents, Depending on the amount of NGINX / Kong services (typically the number of cores), you can read more [here](https://docs.openappsec.io/troubleshooting/troubleshooting-guides/the-first-requests-are-not-recognized-by-the-agent).

Regarding the SaaS Cloud management, can you please elaborate on the issue? 

Thanks!

**Comment by daniynwa** [comment]
Hi @orianelou 

thanks for discus.
