### ISSUE TITLE
label:"help wanted" I need to use Declarative policy hence have few doubts about it

### ISSUE THREAD

**Issue by Blason** [openappsec/openappsec#76]
Hi Team,

So if I want to manage policy using declarative statements. 

1. I need to edit local_policy.yaml file?
2. Then writing down statements as mentioned in local_policy.yaml is sufficient?
3. Because when I see policy is being managed by opeappsec.io portal; I see policy is created in json file which is policy.json
4. Do I need to write that as well?
5. Or can I use the existing policy from one instance to another?

Can you please help me on understanding policies when management is through declarative and through portal?

**Comment by orianelou** [comment]
Hi, 

You only need to create a YAML policy file, and the open-appsec agent parses the policy file into a JSON, for your interest you can find that JSON at etc/cp/conf/policy.json.
