### ISSUE TITLE
get logs data displayed in UI Portal, directly from the VM  (Docker Centrally Managed)

### ISSUE THREAD

**Issue by shubhshah01** [openappsec/openappsec#78]
Where can i see the logs in the vm ? The same logs which i see on the portal ?
In the mounted dirs i have /logs folder but the content doesnt seem to be readable.

Basically, where is the data stored and how can i get it in a readable format ?

![image](https://github.com/openappsec/openappsec/assets/122277028/e1099d97-93ea-4dfb-a506-055605eafb6a)

**Comment by Blason** [comment]
the files are in json format and transaction logs are cp-nano-http-transaction-handler.log. If you have jq installed and have proficiency with jq you will be able to easily parse those logs. Or use third party tool like opensearch or ELK stack

**Comment by shubhshah01** [comment]
@Blason thanks for that quick response.

I had few qns,
1. So the screenshot I've shared is the correct location of where the data is stored ? (its the mounted dir)
2. Which file has my transaction logs ? (I don't see any json format file)
3. Is web UI populated from here only or does it get data from some place else ? If some other place then from where ?

**Comment by shubhshah01** [comment]
yes /var/log/nano_agent is the path mounted at the above shared screenshot location.
Sorry if i am asking obvious/silly qns.
can u tell the file which has the transaction logs ? 
Is it cp-nano-http-transaction-handler.log1 and cp-nano-http-transaction-handler.log2 files ? 
It only has "Web AppSec Policy Loaded Successfully" events. not the other actual http traffic events.

Is there any other configuration required ?

**Comment by shubhshah01** [comment]
@orianelou sorry for the tag, but would be helpful if u can confirm the below things.

1. Are the logs only stored locally in the VM ?
2. Does the portal get the data directly from VM or is there some other location where the data is stored ? If not, Any link/policy where these things are mentioned would be really really helpful.

**Comment by Blason** [comment]
can u tell the file which has the transaction logs ? - cp-nano-http-transaction-handler.log2 - It rotates every now and then
Is it cp-nano-http-transaction-handler.log1 and cp-nano-http-transaction-handler.log2 files ? Those are rotated hence latest will stored
It only has "Web AppSec Policy Loaded Successfully" events. not the other actual http traffic events. - Do you have any application configured? what does open-appsec-ctl -s gives you
Are the logs only stored locally in the VM ? yes logs are stored locally
Does the portal get the data directly from VM or is there some other location where the data is stored ? If not, Any link/policy where these things are mentioned would be really really helpful. Policies are configured on portal if management mode is selected. If it is configured as declarative then you need to configure the policy manually and apply it. If configured as management then policies are configured on portal and once you do enforce then those are downloaded by agent and stored in /etc/cp/conf/
