### ISSUE TITLE
[Docker] Transfer Advanced ML model learnings

### ISSUE THREAD

**Issue by shubhshah01** [openappsec/openappsec#79]
How can I transfer model learnings to another VM setup to install the exact same thing to another setup with all the existing learnings.
I am using advanced ml model.

**Comment by orianelou** [comment]
Hi @shubhshah01, 

You can use our Web UI, https://my.openappsec.io/. As long as you connect both agents to the same profile they can share learning. You can see more [here](https://docs.openappsec.io/getting-started/using-the-web-ui-saas). 

Please note that currently this is only supported for fully managed mode, and we plan to add support for a declarative management mode very soon as well. 

Best,

Oriane
open-appsec team
