### ISSUE TITLE
Unsupported arch gives misleading error: "Unsupported NGINX version"

### ISSUE THREAD

**Issue by adam-hulin** [openappsec/openappsec#80]
### Problem:
I was following the [Install open-appsec for linux](https://docs.openappsec.io/getting-started/start-with-linux/install-open-appsec-for-linux) on a machine running **aarch64** Ubuntu Jammy + nginx 1.24.0-1-jammy.

```
./open-appsec-install --auto
open-appsec for NGINX and Kong Installer v1.2245.1
For release notes and known limitations check:
https://docs.openappsec.io/release-notes
Searching local NGINX…
NGINX version found: 1.24.0-1-jammy
Downloading open-appsec NGINX attachment... stored in '/tmp/open-appsec'
Unsupported NGINX version, for supported platforms, OS and NGINX versions please see docs.openappsec.io
Downloading open-appsec agent... stored in '/tmp/open-appsec'
Unsupported OS, for supported platforms, OS and NGINX versions please see docs.openappsec.io
```

1. **Unsupported NGINX version**, for supported platforms, OS and NGINX versions please see docs.openappsec.io
(The script should probably stop here due to the error but it tries to download the agent as well.)
2. **Unsupported OS**, for supported platforms, OS and NGINX versions please see docs.openappsec.io

The actual problem has nothing to do with Ubuntu Jammy or nginx 1.24.0-1-jammy, it's that the machine is running aarch64.

### Expected behavior:
I took a look in the install script and noted that it checks whether the _combination_ of arch, distro name and distro version is supported. It also grabs the name of the installed nginx package, but that isn't used for validation.

0. Since the script checks the installed nginx version (and has error messages about it), I expect the script to actually validate whether I'm running a supported nginx package. I couldn't find such a check in the install script. Since a list of supported nginx-packages exists, a simple curl + grep could be used.
```
supported_nginx=$(curl -s https://downloads.openappsec.io/packages/supported-nginx.txt | ${NGINX_VERSION})
if [ "$supported_nginx" != 0 ]; then
     echo "Unsupported NGINX package: ${NGINX_VERSION}. Please see docs.openappsec.io for supported versions."
  exit 1
fi
```

1. I expect the error message to tell me what failed. If the check is (arch && distro name && distro version) == unsupported, tell the user exactly that. ie "The combination of Ubuntu Jammy on aarch64 is unsupported".
As as user I appreciate if the variables that are checked can be seen. That can be very helpful.

It would be better if the installer could check what the problem is, by checking arch, distro name and distro version in order. For example by doing three calls with curl.
```
curl https://downloads.openappsec.io/packages/agent/aarch64/
if fail = Unsupported arch. Aarch64 is not a supported arch.
curl https://downloads.openappsec.io/packages/agent/aarch64/ubuntu/
if fail = Unsupported OS. Ubuntu is not supported on aarch64.
curl https://downloads.openappsec.io/packages/agent/aarch64/ubuntu/jammy/openappsec-jammy.tar.gz
if fail = Unsupported OS version. Ubuntu Jammy is not supported for Aarch64.
```

3. Doing the same check twice should result in the same error message.
Checking (arch + distro name + distro version) twice shouldn't result in one message about OS and one about nginx.

4. Since the first install step fails, I expect the installer to stop rather than continuing to install the next package.

5. If only x86_64 is supported in the installer, the "getting started with linux page" should state so, rather than saying "A Linux machine with A supported OS and NGINX or Kong version.".

6. If only x86_64 is supported, the list mentioned; "A list of all supported/pre-compiled attachments for NGINX and Kong per supported OS versions" should state what arch it supports.

### Details
I took a look at how the error messages are being generated:
```
nginx_curl=$(curl -s -w "%{http_code}" \
        https://downloads.openappsec.io/packages/nginx-attachment/${ARCHITECTURE}/${RELEASE_NAME}/${RELEASE_VERSION_CODENAME}/${encoded_ngx_version}.tar.gz  \
        --output ${OPEN_APPSEC_DOWNLOAD_PATH}/${NGX_FULL_VERSION}.tar.gz)
...
if [ "$nginx_curl" != 200 ]; then
     echo "Unsupported NGINX version, for supported platforms, OS and NGINX versions please see docs.openappsec.io"
     CURL_FAILIURE=true
fi
```

```
agent_packages_curl=$(curl -s -w "%{http_code}" \
            https://downloads.openappsec.io/${PACKAGES_FOLDER}/agent/${ARCHITECTURE}/${RELEASE_NAME}/${RELEASE_VERSION_CODENAME}/openappsec-${RELEASE_VERSION_CODENAME}.tar.gz \
            --output ${OPEN_APPSEC_DOWNLOAD_PATH}/openappsec.tar.gz)
...
    if [ "$agent_packages_curl" != 200 ]; then
            echo "Unsupported OS, for supported platforms, OS and NGINX versions please see docs.openappsec.io"
            CURL_FAILIURE=true
    fi
```

Running the script with set -x I can get the effective urls from the two excerpts.
```
https://downloads.openappsec.io/packages/nginx-attachment/aarch64/ubuntu/jammy/ngx%5fmodule%5f1%2e24%2e0%2d1%2djammy.tar.gz
https://downloads.openappsec.io/packages/agent/aarch64/ubuntu/jammy/openappsec-jammy.tar.gz
```
Both these calls returns HTTP403. Replacing aarch64 with x86_64 results in HTTP200.

### Documentation
The error message mentions reading docs.openappsec.io

[Install open-appsec for linux:](https://docs.openappsec.io/getting-started/start-with-linux/install-open-appsec-for-linux) doesn't mention arch as a prereq.
```
Linux machine with:
 * A supported OS and NGINX or Kong version.
   A list of all supported/pre-compiled attachments for NGINX and Kong per supported OS versions is available.
   In case your versions are not supported yet, you can also build the code yourself, see here.
 * Root permissions 
 * wget command-line tool installed on your linux machine
```

The list of [supported/pre-compiled attachments for NGINX and Kong per supported OS versions](https://downloads.openappsec.io/packages/supported-nginx.txt) doesn't mention arch.
But it says that Ubuntu Jammy + nginx 1.24.0-1-jammy is a supported combination.
```
	jammy:
		nginx:
			1.1.1
                        ...
			1.24.0-1-jammy
                        ...
```

Lastly I tried to google this, in case I've missed something obvious:
site:openappsec.io "aarch64" 0 results
site:openappsec.io "x86_64" 0 results
open-appsec "Unsupported NGINX version" 0 results
"Unsupported OS, for supported platforms, OS and NGINX versions please see docs.openappsec.io" 0 results

**Comment by orianelou** [comment]
Hi @adam-hulin, 

Thank you for your detailed instructions, your contribution is greatly appreciated, and we're looking into adding this check to our next release. 

Thank you again!

Best,

Oriane
open-appsec team
