### ISSUE TITLE
open-appsec for TLS and MTLS traffic

### ISSUE THREAD

**Issue by vinoddampuru-tw** [openappsec/openappsec#81]
Hi,
We have Nginx reverse proxy which terminates both TLS & MTLS traffic. We are evaluating open-appsec as WAF for the reverse-proxy. 

Wanted to understand how openapp-sec can inspect the request body for TLS & MTLS traffic. Will the attachment forward the data to HTTP Transaction handler after the request body is decrypted ?

**Comment by orianelou** [comment]
Hi @vinoddampuru-tw,

Yes, open-appsec is an application layer WAF that integrates directly with NGINX and can inspect the request body for both TLS and MTLS traffic after NGINX decrypts the traffic.

If you have any questions about the deployment of open-appsec you're welcome to ask here or email us at info@openappsec.io.

Best, 
Oriane
open-appsec team
