### ISSUE TITLE
Helm repository / Versioned download URL

### ISSUE THREAD

**Issue by swissbuechi** [openappsec/openappsec#84]
Is there a public Helm repo available for this chart: <https://downloads.openappsec.io/packages/helm-charts/nginx-ingress/open-appsec-k8s-nginx-ingress-latest.tgz>

Or is there maybe a versioned URL like: `https://downloads.openappsec.io/packages/helm-charts/nginx-ingress/open-appsec-k8s-nginx-ingress-<version>.tgz`

Also, why is the chart in this repo not up to date? (Version 4.8.3 instead of 4.8.4)
<https://github.com/openappsec/openappsec/tree/main/build_system/charts/open-appsec-k8s-nginx-ingress>

I want to deploy the helm chart using terraform, currently I need to store the whole `.tgz` file in my repo.

Awesome project, thanks in advance.

**Comment by orianelou** [comment]
Hi @swissbuechi,

Thank you for reaching out and for your interest in our project! We appreciate your support.

Regarding your inquiry about a public Helm repo or versioned URLs for our NGINX Ingress Helm chart, currently, we don't have a public Helm repo or versioned URLs. We understand the importance of these features and are actively working on adding them in the near future.

As for the discrepancy in versions between the Helm versions, we are constantly working to ensure that the latest versions are reflected in the repository and will have this updated soon. 

If you have any specific requirements or encounter issues, please let us know, and we'll be happy to assist you. Thank you for your understanding.

Best regards,

Oriane
open-appsec team

**Comment by swissbuechi** [comment]
Thank you for your reply.
I'm looking forward to these features being implemented.

**Comment by orianelou** [comment]
Hi @swissbuechi, 

We've updated the Helm Chart and it's now based on version 4.9.0 NGINX Ingress Controller. 
Also, starting from this open-appsec version you can pull a versioned helm, just replace the latest tag with our version (for example https://downloads.openappsec.io/packages/helm-charts/nginx-ingress/open-appsec-k8s-nginx-ingress-1.1.3.tgz) 

Have a happy new year, 

Oriane
open-appsec team

**Comment by elraro** [comment]
Hello! Any news about the public Helm repository @orianelou ? I want to try openappsec with Flux in my k8s cluster, but I cant do GitOps without this repo :)

Thank you!
