### ISSUE TITLE
Agent HTTP Transaction Handler Wont Run

### ISSUE THREAD

**Issue by nekromantik** [openappsec/openappsec#87]
hello

i followed instructions on setting up openappsec with nginx on docker and ran the docker command with --standalone but when I do status on the agent it says centrally managed and policy has load error.
anyway I can change the config to local without destroying and re-creating?

>
```
 ---- open-appsec Nano Agent ----
Version: 1.1.3-open-source
Status: Running
AI model version: Simple model V1.0
cat: /etc/cp/conf/agent_details.json: No such file or directory
Management mode: Cloud management (Visibility mode)
Policy files:
    /etc/cp/conf/local_policy.yaml
Policy load status: Error
Last policy update: 2023-12-22T23:45:26.839833

---- open-appsec Orchestration Nano Service ----
Type: Public, Version: 1.1.3-open-source, Created at: 2023-12-21T18:05:56+0000
Status: Running

---- open-appsec Attachment Registrator Nano Service ----
Type: Public, Version: 1.1.3-open-source, Created at: 2023-12-21T18:05:56+0000
Status: Running

---- open-appsec Http Transaction Handler Nano Service ----
Type: Public, Version: 1.1.3-open-source, Created at: 2023-12-21T18:05:56+0000
Status: Ready
```

log for the http handler install

```
Starting installation of Check Point HTTP Transaction Handler service [Sat Dec 23 15:35:05 UTC 2023]

cp: cannot stat 'conf/cp-nano-ips-protections.json': No such file or directory
chmod: cannot access '/etc/cp/conf/data/cp-nano-ips-protections.data': No such file or directory
cp: cannot stat 'resources/cp-ab.js': No such file or directory
cp: cannot stat 'resources/cp-csrf.js': No such file or directory
chmod: cannot access '/etc/cp/conf/waap/cp-ab.js': No such file or directory
chmod: cannot access '/etc/cp/conf/waap/cp-csrf.js': No such file or directory
Requested to restart service '/etc/cp/HttpTransactionHandler/cp-nano-http-transaction-handler', but it is not registered
Installation completed successfully.
```

**Comment by orianelou** [comment]
Hi @nekromantik, 

Have you solved the issue? If not we're here to help! 

The transaction handler will start once the agent has gotten some traffic, as can be described [here](https://docs.openappsec.io/troubleshooting/troubleshooting-guides/the-first-requests-are-not-recognized-by-the-agent).

Regarding the issue with the failed policy load, we couldn't recreate it, but we'll be happy to help you set up your environment, you can fill out the form [here](https://www.openappsec.io/support) and we'll get back to you.

Best,

open-appsec team

**Comment by nekromantik** [comment]
> Hi @nekromantik,
> 
> Have you solved the issue? If not we're here to help!
> 
> The transaction handler will start once the agent has gotten some traffic, as can be described [here](https://docs.openappsec.io/troubleshooting/troubleshooting-guides/the-first-requests-are-not-recognized-by-the-agent).
> 
> Regarding the issue with the failed policy load, we couldn't recreate it, but we'll be happy to help you set up your environment, you can fill out the form [here](https://www.openappsec.io/support) and we'll get back to you.
> 
> Best,
> 
> open-appsec team

hi

i switched to cloud managed to get past the policy issue but the errors in the transaction handler log never went away and it never saw any traffic. I dont have time at the moment so closed the issue. Will try again in new year and contact you if same issue persists. Have a good Christmas!
