### ISSUE TITLE
[Feature Request] Create Docker Swag Add On

### ISSUE THREAD

**Issue by nekromantik** [openappsec/openappsec#88]
Hello
So I know there is instructions on using openappsec with SWAG docker container, However having to build the module every time SWAG gets updated becomes a issue. Will it be possible to add a Docker Mod for SWAG for the nginx attachment? With this it will be available for anyone to use on docker mods and you can update it every time you make changes to the code etc. 

This means you wont have to fork the container and maintain a different image. 

here is the instructions: https://github.com/linuxserver/docker-mods

**Comment by orianelou** [comment]
Hi @nekromantik, 

Thank you for the feedback! We'll look into this.

**Comment by orianelou** [comment]
Hi @nekromantik, 

We are excited to introduce the integration of open-appsec WAF with Docker SWAG! You can find full information in our docs and blog 
https://www.openappsec.io/post/announcing-open-appsec-waf-integration-with-docker-swag-secure-web-application-gateway
https://docs.openappsec.io/integrations/docker-swag 

We'll be happy if you could test it out and let us know what you think!

**Comment by hardwareadictos** [comment]
Why not instead modifying official SWAG container it's not possible to create a SWAG MOD like others do?

```DOCKER_MODS: 'ighcr.io/linuxserver/mods:swag-crowdsec|linuxserver/mods:swag-dashboard|DOCKER_MODS=linuxserver/mods:swag-dbip'``

People might not be confortable deploying a modified official version of a reverse proxy.
