### ISSUE TITLE
Updating from basic to advanced ML

### ISSUE THREAD

**Issue by novastream** [openappsec/openappsec#90]
Sorry, i don't think this is a bug.. I just don't understand the instructions on enabling the advanced ML on Linux embedded client.

I've created the advanced-model direectory at /advanced-model and placed the advanced-model archive inside it and restarted the agent.

What am I doing wrong? :)

**Comment by orianelou** [comment]
Hi @novastream, 

Thank you for the feedback, we've updated the instructions:

1. Create a folder under the following path in the root directory: /advanced-model `mkdir -p /advanced-model`
2. Copy the .tgz file into the folder you created `cp ./open-appsec-advanced-model.tgz /advanced-model/open-appsec-advanced-model.tgz`.
3. Deploy the embedded agent
4. if you already have an open-appsec agent running:
	a. Complete steps 1-3
	b. Run `open-appsec-ctl --stop-agent`
	c. Extract model to the relevant folder by running 
	`tar -xzf /advanced-model/open-appsec-advanced-model.tgz -C /etc/cp/conf/waap`
	d. Run `open-appsec-ctl --start-agent`

Best, 

open-appsec team

**Comment by novastream** [comment]
Thanks! 

Worked great! :)
