### ISSUE TITLE
Make package issue

### ISSUE THREAD

**Issue by lockevod** [openappsec/openappsec#93]
Hello, I'm triying to compile (alpine arm64) and the process is ok, but I've a issue with last step make package
The problem, i think is with the path... I execute the step in openappsec folder and I have this error:

[  0%] Generating ../../build_out/install-cp-nano-agent.sh
/bin/sh: ../../build_system/tools/packaging/makeself_wrapper.sh: Permission denied
make[3]: *** [nodes/orchestration/CMakeFiles/make_package_orchestration.dir/build.make:73: build_out/install-cp-nano-agent.sh] Error 126

The error is normal (I think) because buil-out is the current folder not ../..)

Regards

**Comment by lockevod** [comment]
File exist in directory and it's readable 

alpine:~/devel/openappsec$ ls -la build_system/tools/packaging/makeself_wrapper.sh 
-rw-r--r--    1 sergi    sergi          516 Jan 17 11:31 build_system/tools/packaging/makeself_wrapper.sh

**Comment by lockevod** [comment]
The problem is not the route.. I think it's lack of compatibility with arm64

**Comment by orianelou** [comment]
Hi, 

We're working on providing adjusted instructions for compilation that will be suitable for ARM as well. 

I'm closing this issue and will update [here](https://github.com/openappsec/openappsec/issues/19) on any progress.

**Comment by mdunc** [comment]
@orianelou That ticket was closed and locked and I don't see any update regarding ARM compatibility.  I've been able to get everything to compile, but extraction fails:

```
Check Point agent intelligence service (Version 1.2429.961498) install package
Verifying archive integrity...  100%   All good.
Uncompressing...Extraction failed.
  100%  Signal caught, cleaning up
```

**Comment by orianelou** [comment]
Hi @mdunc, 

This ticket was closed as this one (linked in the latest comment) #231 is still open as a discussion, we prefer not to keep multiple tickets for the same issue 😄
