### ISSUE TITLE
Failed to send web response body

### ISSUE THREAD

**Issue by cm91** [openappsec/openappsec#95]
Hi, 

i've created a Web User Response and linked it to my assets.
Unfortunately when triggering a request that gets blocked, just a blank page is visible in the browser window.
Browsers dev tool shows a 403 which is expected.

Attached you can see a screenshot of my Web User Response config.

The nginx-attachment is logging the following when triggering a request:
`ngx_http_cp_finalize_rejected_request@ngx_cp_custom_response.c:323 [uid 1 | pid 22] <session id 7> | Failed to send web response body`

Thanks,
Christian
![403-response](https://github.com/openappsec/openappsec/assets/38283101/c7f4fee0-c66a-4a02-9de6-46045ab64233)

**Comment by orianelou** [comment]
Hi @cm91, 

Thank you for reporting this, we have successfully recreated the issue, and are looking into it. 

I'll update here on any progress we make.

Best,

open-appsec team

**Comment by orianelou** [comment]
Hi, 

The issue was fixed as part of our 1.1.10 release, thank you for your patience!
